### ISSUE TITLE
银行支付时的setDefaultBank问题

### ISSUE THREAD

**Issue by hubs** [lokielse/omnipay-alipay#10]
使用银行支付时,必须要指定默认银行，我在代码中看到

    public function purchase(array $parameters = array())
    {
        $this->setService($this->service_name);
        $this->setParameter('paymethod', 'bankPay');
        if ($this->getParameter('defaultbank') === null) {
            throw new InvalidRequestException("The setDefaultBank(x) method is not called.");
        }
        return $this->createRequest('\Omnipay\Alipay\Message\ExpressPurchaseRequest', $parameters);
    }

而我使用
    public function setDefaultBank($value)
    {
        $this->setParameter('default_bank', $value);
    }
时字段名为 default_bank ，导致二个key的名称不一致,是不是不是这样写的？

**Comment by lokielse** [comment]
你的意思是defaultbank需要改成default_bank么？
你手动改成default_bank试一试，如果可以请反馈。

**Comment by hubs** [comment]
嗯，我就是手动改成default_bank就可以了

**Comment by lokielse** [comment]
好的 代码已更新~
