### ISSUE TITLE
参数规范问题

### ISSUE THREAD

**Issue by feelsad** [lokielse/omnipay-alipay#105]
你好，

OmniPay 官方推荐各个参数命名统一
比如订单 就叫 transactionId

但是你在omnipay-alipay和omnipay-wechatpay中订单号使用out_trade_no
而在omnipay-unionpay中 订单号使用 orderId，其他一些别的参数也各不相同

参数不同就需要针对不同支付网关依次判断。

能否规范一下参数：
官方参数参考
[Omnipay\Common\Message\AbstractRequest](https://github.com/thephpleague/omnipay-common/blob/master/src/Common/Message/AbstractRequest.php)

**Comment by lokielse** [comment]
> 非常棒的建议！以前没有注意到这个细节，光想着赶紧撸出来给你们用了完事

## 实用性角度

主要还是说明文档不健全导致你们使用不便，支付宝的我写了一下wiki，而微信和银联的文档几乎没有。我这边提供的lib请求基本都是按照支付平台提供的说明文档来命名的，使用的时候可以看一下相关Request里面的代码。

## 优(shu)美(sheng)性(qi)角度

你这个建议非常的到位，如果所有的代码都能像Laravel那样有气质，头发也能少白几根。。。

## 兼容性角度
要做到兼容的方式也是很简单的，就是重写相关参数的`getter`和`setter`。

## 我的角度
开源项目，大家共同努力，欢迎你以及有同样诉求的朋友进行PR（本人近来业务繁忙，focus不在这里，能力有限，照顾不周，还望见谅！）优秀和优美的代码靠大家了！

**Comment by gaodacheng** [comment]
我打算出一份力。

我将会单独开一个issue表明我要做的事儿。

**Comment by php-cpm** [comment]
我fork了一份代码并打算按ping++的字段定义来统一传入参数

**Comment by feelsad** [comment]
Come on , Body
