### ISSUE TITLE
晕, defaul_tbank 打错了

### ISSUE THREAD

**Issue by hubs** [lokielse/omnipay-alipay#11]
<pre><code>
    public function purchase(array $parameters = array())
    {
        $this->setService($this->service_name);
        $this->setParameter('paymethod', 'bankPay');
        if ($this->getParameter('defaul_tbank') === null) {
            throw new InvalidRequestException("The setDefaultBank(x) method is not called.");
        }
        return $this->createRequest('\Omnipay\Alipay\Message\ExpressPurchaseRequest', $parameters);
    }
</code></pre>

是default_bank

**Comment by lokielse** [comment]
已纠正！
