### ISSUE TITLE
无法require到这个包~

### ISSUE THREAD

**Issue by xlkit456852** [lokielse/omnipay-alipay#111]
如下错误：

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install lokielse/omnipay-alipay v2.3.5
    - Conclusion: don't install lokielse/omnipay-alipay v2.3.4
    - Conclusion: don't install lokielse/omnipay-alipay v2.3.3
    - Conclusion: don't install lokielse/omnipay-alipay 2.3.2
    - Conclusion: don't install lokielse/omnipay-alipay v2.3.1
    - Conclusion: don't install lokielse/omnipay-alipay v2.3.0
    - lokielse/omnipay-alipay v2.1.0 requires omnipay/common ~2.1.0 -> satisfiable by omnipay/common[v2.1.0].
    - Conclusion: don't install omnipay/common v2.1.0
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.10
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.9
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.8
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.7
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.5
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.4
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.3
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.2
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.1
    - Conclusion: remove symfony/event-dispatcher v3.2.6
    - Conclusion: don't install symfony/event-dispatcher v3.2.6
    - omnipay/common v2.3.4 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - omnipay/common 2.4.0 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - omnipay/common 2.5.2 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - omnipay/common v2.4.1 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - omnipay/common v2.5.0 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - omnipay/common v2.5.1 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
……………………
………………
………………

**Comment by gaodacheng** [comment]
@xlkit456852  请把你的composer.json放出来，看一看。

**Comment by xlkit456852** [comment]
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "earnp/zmxy": "dev-master",
        "encore/laravel-admin": "1.3.*",
        "intervention/image": "^2.3",
        "laravel/framework": "5.3.*",
        "laravelcollective/html": "^5.3.0",
        "maatwebsite/excel": "^2.1",
        "overtrue/wechat": "^3.2",
        "predis/predis": "^1.1",
        "simplesoftwareio/simple-qrcode": "1.3.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },
    "autoload": {
        "classmap": [
            "database",
            "app/Services/Alipay"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "repositories": {
        "packagist": {
            "type": "composer",
            "url": "https://packagist.phpcomposer.com"
        }
    }
}

```

**Comment by php-cpm** [comment]
我好像是看omnipay的readme里说的，装一下symfony/event-dispatcher 的2.x版本

**Comment by lokielse** [comment]
你按照README里面的方式安装一下试一试，先修改composer.json 再执行 `composer update`

勿直接使用`composer require xxx`

**Comment by xlkit456852** [comment]
这样不会把其他依赖都更新了吗。。其他的可不能更新呀。。

**Comment by xlkit456852** [comment]
已解决！的确是要通过composer update才行！

**Comment by gdc5p** [comment]
已解决，就请关闭issue吧。
