### ISSUE TITLE
手机网站支付有返回trade_no的方法吗？

### ISSUE THREAD

**Issue by xlkit456852** [lokielse/omnipay-alipay#112]
正在用支付宝的JSAPI的快捷支付，需要获得从服务端生成的trade_no，但是现在的手机网站支付好像只有跳转url，没有获取trade_no的方法？

**Comment by xlkit456852** [comment]
很急。。有没有大神来解答下？？

**Comment by gaodacheng** [comment]
支付宝没有JSAPI快捷支付吧，你的支付场景是什么呢

**Comment by xlkit456852** [comment]
好像有吧，jsapi里有个快捷支付，是后端提供统一下单后的trade_no，然后js发起支付

**Comment by gaodacheng** [comment]
微信支付里才有。生成预支付id。

**Comment by xlkit456852** [comment]
https://myjsapi.alipay.com/jsapi/native/trade-pay.html 我是看的这个文档，这个是jsapi支付吗？因为我不想支付后跳url，想直接在callback函数里处理逻辑，才找到这个。

**Comment by xlkit456852** [comment]
大神来解答下吧o(╥﹏╥)o

**Comment by lokielse** [comment]
@xlkit456852 刚添加了新网关来支持你的需求，请用`Alipay_AopJs`网关

https://github.com/lokielse/omnipay-alipay/blob/bff18827298add9f383846f471e7727da7e280f7/src/AopJsGateway.php#L13

**Comment by xlkit456852** [comment]
太好了，感谢！

**Comment by gdc5p** [comment]
@xlkit456852  你可以用了吗，这个issue可以关闭了吧
