### ISSUE TITLE
Alipay_AopPage 支付时错误

### ISSUE THREAD

**Issue by pangxioujiang** [lokielse/omnipay-alipay#113]
biz_content   这个参数是必须填写的， 
Omnipay \ Common \ Exception \ InvalidRequestException
The biz_content parameter is required

**Comment by gaodacheng** [comment]
你的具体代码，可不可以发一下？

> 注意把敏感数据去除后再上传代码。

**Comment by pangxioujiang** [comment]
$gateway = Omnipay::create('Alipay_AopPage');
$gateway->setSignType('RSA2'); //RSA/RSA2
$gateway->setAppId('2014072300007148');
$gateway->setPrivateKey('sdsdfdfdfdfdddddddddddd);
$gateway->setAlipayPublicKey('the_alipay_public_key');
$gateway->setReturnUrl('https://www.example.com/return');
$gateway->setNotifyUrl('https://www.example.com/notify');
$request = $gateway->purchase();

$request->setBizContent([
    'out_trade_no' => date('YmdHis') . mt_rand(1000, 9999),
    'total_amount' => 0.01,
    'subject'      => 'test',
    'product_code' => 'FAST_INSTANT_TRADE_PAY',
]);
$response = $request->send();

$redirectUrl = $response->getRedirectUrl();
$response->redirect();

**Comment by gdc5p** [comment]
目前我这边的支付宝账号冒似有点问题，老是提示我：

```
PHP Warning:  openssl_sign(): supplied key param cannot be coerced into a private key in /home/gdc/work/alipay-app/vendor/lokielse/omnipay-alipay/src/Common/Signer.php on line 150

Warning: openssl_sign(): supplied key param cannot be coerced into a private key in /home/gdc/work/alipay-app/vendor/lokielse/omnipay-alipay/src/Common/Signer.php on line 150
PHP Warning:  openssl_free_key() expects parameter 1 to be resource, boolean given in /home/gdc/work/alipay-app/vendor/lokielse/omnipay-alipay/src/Common/Signer.php on line 159

Warning: openssl_free_key() expects parameter 1 to be resource, boolean given in /home/gdc/work/alipay-app/vendor/lokielse/omnipay-alipay/src/Common/Signer.php on line 159
```

准备复现你的问题，请稍等。

**Comment by lokielse** [comment]
@pangxioujiang 老铁，我刚测试了一下，设置了`biz_content`不会有异常，没设置和设置了一个空的值会有这个异常，请检查你传入`setBizContent`方法的参数是否为空。

请在`setBizContent`后取出值打印一下
```php
$request->setBizContent(...);
var_dump($request->getBizContent());
```

**Comment by gdc5p** [comment]
@pangxioujiang 

> 我这边的支付宝账号弄好了，证书配置问题。

但是无法复现你的问题的。
