### ISSUE TITLE
 guzzle/guzzle 这个包被放弃了，不再维护

### ISSUE THREAD

**Issue by pangxioujiang** [lokielse/omnipay-alipay#115]
这个包被放弃了，不再维护。作者建议使用guzzlehttp / guzzle包来代替。
This package is abandoned and no longer maintained. The author suggests using the guzzlehttp/guzzle package instead.

**Comment by gdc5p** [comment]
@pangxioujiang 

这个依赖的产生原由是：

```bash
$ composer why guzzle/guzzle
omnipay/common  2.5.2  requires  guzzle/guzzle (~3.9)
```

仍然是可以使用，估计在以后的版本中会渐渐使用新的依赖。

通过查看 omnipay/common 仓库的最新git进展，在3.0的版本中不再使用guzzle库，改用其他得了。

**Comment by php-cpm** [comment]
我fork了一个分支，composer库名 php-cpm/omnipay

基于omnipay/common 3.0 开发的，尚无稳定版本，欢迎试用反馈
