### ISSUE TITLE
这个包只有支付没有其他接口么？退款查账之类的

### ISSUE THREAD

**Issue by llons** [lokielse/omnipay-alipay#116]

**Comment by gdc5p** [comment]
您需要的接口是什么，可否提供一下您需要的支付宝接口文档地址？

**Comment by llons** [comment]
https://docs.open.alipay.com/api_1/alipay.trade.refund/

**Comment by gdc5p** [comment]
@llons 

您好，这个接口已经有的。

请参见文件： [AopTradeRefundRequest](https://github.com/lokielse/omnipay-alipay/blob/master/src/Requests/AopTradeRefundRequest.php)

**Comment by llons** [comment]
懂了！这命名没谁了 :)。。

**Comment by gdc5p** [comment]
@llons  

Ok，欢迎使用此库。

**Comment by gdc5p** [comment]
请关闭issue吧。
