### ISSUE TITLE
更改 omnipay/common 为 3.0 的想法

### ISSUE THREAD

**Issue by gdc501** [lokielse/omnipay-alipay#117]
请问我们可以使用 omnipay/common 3.0 吗，目前他们处于alpha版本，我们要不要跟上，并且有很多用户也反应了关于 guzzle 库的问题。

**Comment by lokielse** [comment]
@gdc5p 新开个分支大胆搞起来吧， 我看了下`roadmap`，基本是没什么问题的了。

参照一下 ：

https://github.com/fruitcake/omnipay-sisow/pull/5
https://github.com/thephpleague/omnipay-mollie/pull/34
