### ISSUE TITLE
申请成为本库维护者

### ISSUE THREAD

**Issue by gdc501** [lokielse/omnipay-alipay#118]
请问作者有打算招募维护者吗？

如果有此想法，请问有什么要求吗？

我想成为这样一位维护者，目的将本库发扬光大，力求成为在PHP界易用且强大的支付宝第三方SDK。

**Comment by lokielse** [comment]
@gdc5p 欢迎，已邀！

想法及建议：

1. 你可以在[projects](https://github.com/lokielse/omnipay-alipay/projects)中创建一些todo，以便开发交流
2. 尽量测试好后再打标签
3. 尽量保证小版本向前兼容
