### ISSUE TITLE
openssl_sign(): supplied key param cannot be coerced into a private key 还有openssl_free_key() expects parameter 1 to be resource, boolean given

### ISSUE THREAD

**Issue by CaveyChan** [lokielse/omnipay-alipay#119]
我看了下是        
https://github.com/lokielse/omnipay-alipay/blob/master/src/Common/Signer.php#L141
这行
$res        = openssl_pkey_get_private($privateKey);
openssl_pkey_get_private函数发回了false

按照https://github.com/lokielse/omnipay-alipay/wiki/FAQs
我的公钥和私钥传入的都是字符串，
我分析这一行有问题
https://github.com/lokielse/omnipay-alipay/blob/master/src/Common/Signer.php#L229
return implode("\n", $lines);
在Windows和Linux系统中换行符不应该都是\n吧，应该用PHP_EOL，对不对？？？

**Comment by gdc5p** [comment]
不同系统上的文本的换行符是不同。

那么，你如果把 `\n` 改为 `PHP_EOL`，可以解决吗？

**Comment by CaveyChan** [comment]
openssl_pkey_get_private函数出现这种错误
error:0D06C03A:asn1 encoding routines:ASN1_D2I_EX_PRIMITIVE:nested asn1 error
大神知道什么原因吗？

**Comment by CaveyChan** [comment]
我在支付宝中没有看到应用私钥这种东西

**Comment by gdc5p** [comment]
支付宝接口使用一对公钥和私钥。利用 openssl 工具生成。同时还需要使用支付宝公钥。

你配置正确吗？

**Comment by CaveyChan** [comment]
![image](https://user-images.githubusercontent.com/16031190/34663199-9aded268-f490-11e7-87e8-e719b3012ff4.png)

只有公钥没看到私钥

**Comment by gdc5p** [comment]
key(钥)是一对。

上传到支付宝账号配置中心里的没有私钥。

私钥只能存放到本地，不能上传至任何公共地方。

**Comment by CaveyChan** [comment]
刚才看到了私钥，已经解决了。

有一个问题，我为什么传字符串而不是文件，是因为出于数据安全的原因，如果是字符串我可以保存为环境变量，这样本地开发人员就看不到私钥，如果是文件的话，私钥文件很可能被开发人员同步到本地，这样所有的开发人员都看到了，这肯定是不行的，如何保证私钥不泄露？？
有好的想法吗？？

**Comment by gdc5p** [comment]
嗯，你的这种做法是值得肯定得。

基于这种思想[点这儿](https://12factor.net/)，将敏感数据与代码分开是比较安全的。但是这种安全，是相对的。你说开发人员要想看不到这个私钥，不太现实，因为他不正是主角吗，他如果获取不到这私钥，那么他怎么能进行接口调试呢？这里的安全是说与外界之间的隔离，不要将账号等信息放到仓库里即可。
