### ISSUE TITLE
Alipay Sandbox

### ISSUE THREAD

**Issue by Wolfsun** [lokielse/omnipay-alipay#12]
Hi,

Is it possible to use the Alipay Sandbox (testing) account with your alipay plugin? If not, could this be added as an enhancement?

Thanks

**Comment by kinosang** [comment]
Unfortunately, Alipay does not provide any sandbox environment about payment to developers, there's only an imperfect sandbox for Alipay OAuth and AlipayInside.

**Comment by hardywu** [comment]
现在支持sandbox了。
