### ISSUE TITLE
你好 新版本的一个问题 请问回调应该是一样的吧对于我创建的网关会有影响吗

### ISSUE THREAD

**Issue by longlovehong** [lokielse/omnipay-alipay#120]
if($data['user_type'] == 'web'){
			$gateway = Omnipay::create('Alipay_AopPage');//创建网关类
			$product_code = 'FAST_INSTANT_TRADE_PAY';
		}else{
			$gateway = Omnipay::create('Alipay_AopWap');//创建网关类
			$product_code = 'QUICK_WAP_PAY';
		}
我是要适应手机端和电脑端
对于回调的话，，创建的网关类用哪个啊还是都可以。。应该都可以把

**Comment by gdc5** [comment]
@longlovehong  

你好。你说的是异步通知吗？

**Comment by longlovehong** [comment]
$request = $gateway->completePurchase();

**Comment by longlovehong** [comment]
非常感谢你，，这么快回复我，我指的是异步通知，$result = $gateway->completePurchase();他这个$gateway我可以随便实例化是吗$gateway = Omnipay::create('Alipay_AopPage');$gateway = Omnipay::create('Alipay_AopWap');用这两个其中一个都可以是吗都可以是吗

**Comment by longlovehong** [comment]
$gateway = Omnipay::create('Alipay_AopPage');
		$gateway->setSignType(config('laravel-pay.alipay.sign_type')); // RSA/RSA2/MD5
		$gateway->setAppId(config('laravel-pay.alipay.app_id'));
		$gateway->setPrivateKey(config('laravel-pay.alipay.merchant_private_key'));
		$gateway->setAlipayPublicKey(config('laravel-pay.alipay.alipay_public_key'));
		$gateway->setReturnUrl(config('laravel-pay.alipay.return_url'));
		$gateway->setNotifyUrl(config('laravel-pay.alipay.notify_url'));
		$result = $gateway->completePurchase();

**Comment by gdc5** [comment]
@longlovehong  

> `$result = $gateway->completePurchase();`
> 他这个$gateway我可以随便实例化是吗
> `$gateway = Omnipay::create('Alipay_AopPage');`
> `$gateway = Omnipay::create('Alipay_AopWap');`
> 用这两个其中一个都可以是吗

是的。

> 验证一直失败，`$response->isPaid()` 是 `false` , 请问我是哪里出了问题 ?

输出一下 ：

```
$response->getData()
```
