### ISSUE TITLE
lumen 5.6中symfony/http-foundation冲突

### ISSUE THREAD

**Issue by farmercode** [lokielse/omnipay-alipay#126]
lumen中目前使用的是4.x的http-foundation,但是omnipay-common 2.0版本的使用的是较低版本的，目前开发版本omnipay-common dev-3.0使用的是最新版本的。所以需要把omnipay-common升级到dev-master版本。

**Comment by lokielse** [comment]
#127 已升级，邀请你试用，有问题在主贴反馈。

**Comment by farmercode** [comment]
哎呀，你要是早弄好，我就不需要自己弄1个分支发布了，搞了半上午啊！好僵！不过我还是要试试你的！多谢作者！这是我根据你的做了个2次修改的！
https://github.com/farmercode/alipay
