### ISSUE TITLE
请教关于wap异步通知回来问题

### ISSUE THREAD

**Issue by hubs** [lokielse/omnipay-alipay#13]
<pre>
       $gateway = Omnipay::create("Alipay_WapExpress");
        $gateway->setPartner(Config::get('pay.alipay.id'));
        $gateway->setKey(Config::get('pay.alipay.key'));
        $gateway->setSellerEmail(Config::get('pay.alipay.email'));
        $options['request_params'] = Input::all();

        //$options['ca_cert_path']   = storage_path() . '/cert/cacert.pem';
        $options['ca_cert_path']   = storage_path() . '/cert/alipay_public_key.pem';
        $options['private_key']    = storage_path() . '/cert/rsa_private_key.pem';
        $options['sign_type']      = 'MD5';
        $request                   = $gateway->completePurchase($options)->send();
        $out_trade_no = Input::get('out_trade_no');
</pre>

报: openssl_private_decrypt(): key parameter is not a valid private key 异常,
<pre>
        $options['ca_cert_path']   = storage_path() . '/cert/alipay_public_key.pem';
        $options['private_key']    = storage_path() . '/cert/rsa_private_key.pem';
</pre>
这二个是这样写的吗？

**Comment by lokielse** [comment]
ca_cert_path 不是支付宝公钥，是以下的文件

https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt

**Comment by hubs** [comment]
还有个问题请教,在手机wap发送到支付宝时默认的是MD5格式,而返回回来验证又必须是RSA格式..
<pre>
 public function decrypt($str)
    {
        return $this->rsaDecrypt($str, $this->getPrivateKey());
    }
    public function sendData($data)
    {
        $data        = array();
        $notify_data = $this->decrypt($this->getNotifyData());
        $doc         = new DOMDocument();
        $doc->loadXML($notify_data);
        if (!empty($doc->getElementsByTagName("notify")->item(0)->nodeValue)) {
            $out_trade_no = $doc->getElementsByTagName("out_trade_no")->item(0)->nodeValue;
            $trade_no     = $doc->getElementsByTagName("trade_no")->item(0)->nodeValue;
            $trade_status = $doc->getElementsByTagName("trade_status")->item(0)->nodeValue;
            $this->setOutTradeNO($out_trade_no);
            $this->setTradeNO($trade_no);
            $this->setTradeStatus($trade_status);
            if ($trade_status == 'TRADE_FINISHED' || $trade_status == 'TRADE_SUCCESS') {
                $data['verify_success'] = true;
            } else {
                $data['verify_success'] = false;
            }
        }
        return $this->response = new ExpressCompletePurchaseResponse($this, $data);
    }
</pre>

而头部的
<pre>
 public function getData()
    {
        $this->validate('request_params', 'partner', 'private_key');
        $this->validateRequestParams('notify_data', 'trade_status');
        return $this->getParameters();
    }

</pre>
trade_status是包含在notify_data里面的,而不在外面,所以也一直会报错

**Comment by hubs** [comment]
我现在是这样处理的

1、WapExpressCompletePurchaseRequest类
<pre>
    public function getData()
    {
        $this->validate('request_params', 'partner');//, 'private_key',如果是MD5则不用private_key
        //$this->validateRequestParams('notify_data');//, 'trade_status' //return通知时没有notify_data数据,异步中没有trade_status
        return $this->getParameters();
    }

</pre>
sendData()方法 
<pre>
 public function sendData($data)
    {
        switch (strtoupper($this->getSignType())) {
            case "MD5":
                return $this->sendDataMD5($data);
            case "RSA":
            case "0001":
                return $this->sendDataRSA($data);
        }
        return $this->response = new ExpressCompletePurchaseResponse($this, $data);
    }

    public function sendDataMD5($data)
    {
        $data        = array();
        $reqParams   =  $this->getParameters();

        $notify_data = $this->getNotifyData();
        if($notify_data){
            $doc         = new DOMDocument();
            $doc->loadXML($notify_data);
            if (!empty($doc->getElementsByTagName("notify")->item(0)->nodeValue)) {
                $reqParams['request_params']["notify_id"]=$doc->getElementsByTagName("notify_id")->item(0)->nodeValue;
            }
        }
        $request     = new MExpressCompletePurchaseRequest($this->httpClient, $this->httpRequest);
        $request     = $request->initialize($reqParams);
        return $request->sendData($data);
        //return $this->response = new ExpressCompletePurchaseResponse($this, $data);
    }
    public function sendDataRSA($data)
    {
        $data        = array();

        $notify_data = $this->getNotifyData();
        if($notify_data){
            $notify_data = $this->decrypt($notify_data);
            $doc         = new DOMDocument();
            $doc->loadXML($notify_data);
            if (!empty($doc->getElementsByTagName("notify")->item(0)->nodeValue)) {
                $out_trade_no = $doc->getElementsByTagName("out_trade_no")->item(0)->nodeValue;
                $trade_no     = $doc->getElementsByTagName("trade_no")->item(0)->nodeValue;
                $trade_status = $doc->getElementsByTagName("trade_status")->item(0)->nodeValue;
                $this->setOutTradeNO($out_trade_no);
                $this->setTradeNO($trade_no);
                $this->setTradeStatus($trade_status);
                if ($trade_status == 'TRADE_FINISHED' || $trade_status == 'TRADE_SUCCESS') {
                    $data['verify_success'] = true;
                } else {
                    $data['verify_success'] = false;
                }
            }
        }
        return $this->response = new ExpressCompletePurchaseResponse($this, $data);
    }
</pre>

其中增加了 MExpressCompletePurchaseRequest 类,它extends  ExpressCompletePurchaseRequest

<pre>
<?php
namespace Omnipay\Alipay\Message;

use Omnipay\Common\Exception\InvalidRequestException;
use Omnipay\Common\Message\AbstractRequest;

class MExpressCompletePurchaseRequest extends ExpressCompletePurchaseRequest
{
    public function getParamsToSign()
    {
        $params= parent::getParamsToSign(); // TODO: Change the autogenerated stub
        unset($params['notify_id']);
        return $params;
    }

    protected function getParamsSignature($data)
    {
        $method = \Request::method();
        if($method=="GET"){
            return parent::getParamsSignature($data);
        }else{
            $data=$this->sortNotifyPara($data);

            $query_string = http_build_query($data);
            $query_string = urldecode($query_string);

            $sign_type    = $this->getSignType();

            if ($sign_type == 'MD5') {
                $sign = md5($query_string . $this->getKey());
            } elseif ($sign_type == 'RSA') {
                $sign = $this->rsaVerify($query_string, trim($this->getAliPubicKey()), $this->getRequestParam('sign'));
            } elseif ($sign_type == '0001') {
                $sign = $this->rsaVerify($query_string, trim($this->getAliPubicKey()), $this->getRequestParam('sign'));
            } else {
                $sign = '';
            }
            return $sign;
        }
    }

    //异步需要固定这样排序....
    function sortNotifyPara($para) {
        $para_sort['service'] = $para['service'];
        $para_sort['v'] = $para['v'];
        $para_sort['sec_id'] = $para['sec_id'];
        $para_sort['notify_data'] = $para['notify_data'];
        return $para_sort;
    }
}

</pre>

支付宝返回时有二种格式 
1、GET:这个是同步返回的数据 return_url 
我这边返回的数据只包含
<pre>
out_trade_no         alipay_wap_L19186123
request_token        requestToken
result               success
sign                         162f53e6c59e00b54bf245f74dcbe9a3
sign_type                 MD5
trade_no                  2015061100001000280058452708
</pre>

2,POST:异步通知 notify_url
<pre>
[service] => alipay.wap.trade.create.direct
        [sign] => 5044e15a436cd41a0f8d8998b73fad5e
        [sec_id] => MD5
        [v] => 1.0
        [notify_data] => <notify>........</notify>
</pre>

**Comment by lokielse** [comment]
@hubs 你说得对，现已将`WapExpressCompletePurchaseRequest`重做
