### ISSUE TITLE
条码支付同步调用时是否会因为curl超时而中断?

### ISSUE THREAD

**Issue by miaotaizi** [lokielse/omnipay-alipay#132]
老铁好, 你的组件非常好用, 有个问题想请教一下, 在支付宝条码支付下, 会不会因为 支付宝那边的 response 响应较慢, 导致 本地 curl timeout 超时?

因为我们的生产环境经常会发生客户端没收到我们自己服务器的响应, 但是服务端的支付业务成功的情况.

**Comment by lokielse** [comment]
1. 服务器与支付宝方面的网络超时理论上是存在的，虽然实际上几率会非常小。
2. 服务端支付成功，而客户端没有收到响应，既然服务端已经成功了，说明和问题1没有关系了。其实是流程问题，请看下面图解：

<img width="496" alt="default" src="https://user-images.githubusercontent.com/1573211/39692622-f23e9094-5213-11e8-9eee-d9c7087898f4.png">

https://github.com/lokielse/omnipay-alipay/blob/8a98c819a5a9b6e91a207380f41ba93543b0adaa/src/Requests/AopTradePayRequest.php#L56-L86

https://github.com/lokielse/omnipay-alipay/blob/8a98c819a5a9b6e91a207380f41ba93543b0adaa/src/Requests/AopTradePayRequest.php#L48-L50

https://github.com/lokielse/omnipay-alipay/blob/8a98c819a5a9b6e91a207380f41ba93543b0adaa/src/Requests/AopTradePayRequest.php#L141-L146

本库为方便使用，将轮询放在了服务端，使用者可根据实际情况启用和禁用该轮询机制。
你需要做的是：将上述的轮询机制转移到客户端来完成。

**Comment by miaotaizi** [comment]
恩, 这个事情我们正在做, 但是因为目前 app 那边缺那么一些功能, 所以想确认一下这个现象是不是正确的.

另外我想知道的是, 本库使用的 httpClient 是不是 不能去设置超时时间? 或者说他会不会主动超时?
