### ISSUE TITLE
Is Alipay_AopF2F can used by ISV

### ISSUE THREAD

**Issue by carlxjs** [lokielse/omnipay-alipay#149]
Even I use the function of `setAppAuthToken` to set the value of `app_auth_token` in `$gateway.`

But  after `$request = $gateway->capture();`, I can not see the value of `app_auth_token` in `$request`. 
 
So I get the message `isv.self-invoke-forbidden 此用户不允许自调用`    
 https://openclub.alipay.com/read.php?tid=7494&fid=68&ant_source=zsearch

**Comment by skyred** [comment]
As https://github.com/lokielse/omnipay-alipay/issues/153#issuecomment-467327516 suggests, @lokielse can you please roll a new release again to include this new feature?

**Comment by skyred** [comment]
I am maintaining commerce_alipay on https://www.drupal.org/project/commerce_alipay , which requires this commit

**Comment by lokielse** [comment]
@skyred check it out! https://github.com/lokielse/omnipay-alipay/tree/v3.0.5

**Comment by skyred** [comment]
:clap:

**Comment by skyred** [comment]
@lokielse I just realized that packagist.org doesn't have the latest releases from you this week, https://packagist.org/packages/lokielse/omnipay-alipay stays at v.3.0.3. I am not sure if there is a manual process of uploading new tarballs to the packagist.org or there is something broken in the automation?

**Comment by lokielse** [comment]
@skyred Yes, some broken in the automation... It's available now.
