### ISSUE TITLE
ILLEGAL_PARTNER_EXTERFACE

### ISSUE THREAD

**Issue by ivandokov** [lokielse/omnipay-alipay#15]
Once I go to AliPay I see the following message. With some help from Google Translate:

> 调试错误，请回到请求来源地，重新发起请求。
> 错误代码 ILLEGAL_PARTNER_EXTERFACE
> 说明:如果您不是因为本接口集成调试而看见该错误提醒，请联系本次请求来源网站，本错误属于网站集成接口的错误。

> Debug error, please return to the request source, re-initiate the request.
> Error code ILLEGAL_PARTNER_EXTERFACE
> Note: If you are not because of the interfaces integrated debugger and see the error reminder, please contact the source site this request, this error is a wrong site integrated interface.

I have Googled the issue and found that I can change 
```
ExpressGateway -> $service_name = 'create_direct_pay_by_user';
``` 
to
```
ExpressGateway -> $service_name = 'create_forex_trade';
``` 
and then I see another error:
> 调试错误，请回到请求来源地，重新发起请求。
> 错误代码 ILLEGAL_SIGN
> 说明:如果您不是因为本接口集成调试而看见该错误提醒，请联系本次请求来源网站，本错误属于网站集成接口的错误。

> Debug error, please return to the request source, re-initiate the request.
> Error code ILLEGAL_SIGN
> Note: If you are not because of the interfaces integrated debugger and see the error reminder, please contact the source site this request, this error is a wrong site integrated interface.

I have used the following credentials for testing:
```
'id'    => '2088111956092332',
'key'   => '136nflj7uu24i7v6cheubmpy0uav4tdx',
'email' => 'alipay_test@alipay.com',
```
I am really stuck here. I will appreciate any help!

**Comment by lokielse** [comment]
The `email` means `seller_email`, may be your email 'alipay_test@alipay.com' is not  correct.

If your account is international. You have to change service parameter from “create_direct_pay_by_user” to “create_forex_trade”.

**Comment by IvanDokov** [comment]
Oh I see. I though the test account is for merchant, but it seems it is not.
I am really confused with Chinese. I don't understand where I should register as merchant.
My client is from China, but I will test with company account so I guess the client account will be "regular" and our account will be "international". Am I right?

**Comment by lokielse** [comment]
If you do not have an account, you should contact Alipay to get an available api account.

**Comment by IvanDokov** [comment]
Any idea how to contact them? I saw the "Alipay Service Application Form", but they said I will receive phone call. I didn't see any email contact options.

**Comment by lokielse** [comment]
Please visit http://global.alipay.com/service/service.htm

**Comment by IvanDokov** [comment]
This is where I found the Service Application Form by clicking on "Apply Assistance" and "Apply Integration" asks me to login and I do not have account.

**Comment by lokielse** [comment]
Sign Up First https://globalprod.alipay.com/order/emailVerify.htm

**Comment by IvanDokov** [comment]
It looks like I will have to ask the client t sign up there because the info is too detailed about the company.
