### ISSUE TITLE
验签的一个坑，希望大家注意一下。

### ISSUE THREAD

**Issue by mm17835388286** [lokielse/omnipay-alipay#159]
不管是同步验签还是异步验签，回调的url中的参数有很多变化，就好比我用的yii2框架，生成的url中会多一个s参数，这样的话回调签名的时候，就会多加一个s参数进行签名，所以大家一定一定要看清楚，不要直接
$request->setParams(array_merge(Yii::$app->request->post(), Yii::$app->request->get()));
这样可能会多加参数进去，如果没有碰到这个问题的话，请略过。。

**Comment by dongm2ez** [comment]
你是怎么解决的

**Comment by mm17835388286** [comment]
我的yii2框架回调路由中自带了一个s参数，我将整个post和get数据取到后赋给一个变量，然后unset掉s



------------------ 原始邮件 ------------------
发件人: "David Happ"<notifications@github.com>; 
发送时间: 2019年5月6日(星期一) 中午11:26
收件人: "lokielse/omnipay-alipay"<omnipay-alipay@noreply.github.com>; 
抄送: "贾晖荣"<1010762866@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lokielse/omnipay-alipay] 验签的一个坑，希望大家注意一下。 (#159)




你是怎么解决的

**Comment by dongm2ez** [comment]
好的，谢谢


On May 6, 2019 at 13:39:06, mm17835388286 (notifications@github.com) wrote:

我的yii2框架回调路由中自带了一个s参数，我将整个post和get数据取到后赋给一个变量，然后unset掉s



------------------ 原始邮件 ------------------
发件人: "David Happ"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 中午11:26
收件人: "lokielse/omnipay-alipay"<omnipay-alipay@noreply.github.com>;
抄送: "贾晖荣"<1010762866@qq.com>; "Author"<author@noreply.github.com>;
主题: Re: [lokielse/omnipay-alipay] 验签的一个坑，希望大家注意一下。 (#159)




你是怎么解决的
