### ISSUE TITLE
希望可以清理一下从omnipay引入的Tag，然后发布一个正式版本Tag

### ISSUE THREAD

**Issue by CallMeNP** [lokielse/omnipay-alipay#16]
在 https://packagist.org/packages/lokielse/omnipay-alipay 中看到有很多版本，如v2.1.0,v1.1.0。
但是发现只有dev-master能用。其他版本应该是从omnipay中引入的吧？

能否清理一下呢？
因为在我们的项目里，要求每个依赖库都注明明确版本。不允许使用dev-master。这样是为了避免未经测试的更新造成线上环境不稳定。

这个库对我们的项目非常有帮助。期待您的消息。

**Comment by lokielse** [comment]
已删除！目前最新版本`v1.0.0`可用

**Comment by CallMeNP** [comment]
谢谢，相当及时。
