### ISSUE TITLE
能否添加对公钥证书方式的支持

### ISSUE THREAD

**Issue by iuhux** [lokielse/omnipay-alipay#165]
好像现在没有对公钥证书方式签名的支持

**Comment by 0377** [comment]
可以参考这篇文章，配置公钥证书
[https://sbing.vip/archives/2019-new-alipay-php-docking.html](https://sbing.vip/archives/2019-new-alipay-php-docking.html)

**Comment by cmzz** [comment]
@0377 来个pr

**Comment by liu-ai** [comment]
需求+1

**Comment by successgo** [comment]
see #168
