### ISSUE TITLE
Installation failed - conflict of guzzle versions

### ISSUE THREAD

**Issue by PengKuang** [lokielse/omnipay-alipay#182]
Hi, the installation of the gateway failed due to conflict of guzzle versions I couldn't resolve it even with the command suggested. Should I manually downgrade the guzzle version in the composer.json file?

![image](https://user-images.githubusercontent.com/31425596/97824740-bab73200-1cf7-11eb-8e1b-13f51627e861.png)

**Comment by successgo** [comment]
please check your root composer.json which requires guzzlehttp/guzzle 7.0.1, and look for if you can get the balance of guzzle of your root requirement and the alipay package.

**Comment by PengKuang** [comment]
Sorry I don't quite understand the solution you suggested - " look for if you can get **the balance of guzzle of your root requirement and the alipay package.**"

What should I do? Modify the version to 6.0.0 in the composer.json file?

**Comment by PengKuang** [comment]
I fixed the problem by change the version number of guzzle to 6.0.0 in both composer.json and composer.lock:

composer.json:
**"guzzlehttp/guzzle": "^6.0.0",**

composer.lock:
"name": "guzzlehttp/guzzle",
            **"version": "6.0.0",**
            "source": {
                "type": "git",
                "url": "https://github.com/guzzle/guzzle.git",
                "reference": "0aa74dfb41ae110835923ef10a9d803a22d50e79"
            },

 "support": {
                "issues": "https://github.com/guzzle/guzzle/issues",
                **"source": "https://github.com/guzzle/guzzle/tree/6.0.0"**
            },
