### ISSUE TITLE
为什么同样的证书 同样的代码,在不同的平台上获取的RootSN不一样?

### ISSUE THREAD

**Issue by pslxx** [lokielse/omnipay-alipay#187]
![image](https://user-images.githubusercontent.com/8417207/106491967-61c38980-64f2-11eb-8d81-a72190241f25.png)

一个是线上服务器,一个是本机docker里面的
同样的一个账户,,而且我看了代码也是一样的,为什么 下划线后面的部分,竟然不一样
上面的是正确的,下面的的是错误

**Comment by dacheng-gao** [comment]
请问还有问题吗

**Comment by pslxx** [comment]
不管了,反正服务器上是OK 的,具体什么原因也不知道
