### ISSUE TITLE
openssl_sign(): supplied key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by hubs** [lokielse/omnipay-alipay#21]
使用手机支付宝支付时,出现这个异常　.

**Comment by lokielse** [comment]
私钥问题

可能是私钥未设置、路劲不存在、私钥不合法，请检查。

**Comment by flymorn** [comment]
如果服务器是php，支付宝拿到的公钥一定要分行，不能为1行，不然PHP的openssl_pkey_get_public无法读取，并且格式要符合下面的标准格式：

-----BEGIN PUBLIC KEY-----
MIGfMA0GCSDFDFFFQ9L6BkRA
FljhNhgPdyPufQNNiFYnkd3/PrQE
B/VsW8OoM87UDYVOrFXf/B5Ksi
NG9zpgmLCIDAQAB
-----END PUBLIC KEY-----
