### ISSUE TITLE
退款功能貌似不存在

### ISSUE THREAD

**Issue by as5772830** [lokielse/omnipay-alipay#22]
请问实现了退款功能了吗

**Comment by AZ-WH** [comment]
好像真的没有这个功能

**Comment by greyhu** [comment]
有一个带退款分支准备提交合并的，结果分支作者又把pull request取消了。。。苦

**Comment by snowno** [comment]
我本地项目根据这个 拓展了退款功能。。有时间整理一下push上来~

**Comment by lokielse** [comment]
`refund`和`completeRefund`方法已经实现了，可以退款了
