### ISSUE TITLE
Alipay_MobileExpress 返回给客户端的签名是错误的

### ISSUE THREAD

**Issue by unidotnet** [lokielse/omnipay-alipay#26]
公钥私钥都是正确的，就是ios客户端无法使用返回的签名。
 iOS拿 $response->getOrderString() 后返回的参数，不用服务器返回的签名，自己签名是可以的。
貌似签名逻辑有问题，能看下吗？谢谢。

**Comment by lokielse** [comment]
`$response->getOrderString()` 得到的是订单字符串，客户端直接使用它就可发起支付（如下）

这个我已经在正式环境使用过一段时间了，应该是OK的

你可以到`MobileExpressPurchaseRequest`这个类里面去调试一下，看看和你在客户端生成的有何区别。


```Objective-C
//YourController.m
//Click Buy Button
NSString featureId = @"com.example.product.1001";

[APIClient get:@"http://api.example.com/pay/alipay/payto" data:{featureId:featureId, num:1} result:(NSDictionary *result){
    NSLog(@"result2 = %@", result)
   
    [[AlipaySDK defaultService] payOrder:result[@"order_info_str"] fromScheme:@"your-schema" callback:^(NSDictionary *resultDic) {
       //result
    }];
}];
```

**Comment by lichunqiang** [comment]
@lokielse 

在手机支付回调验证的时候，那个public key 需要和在支付宝添加的时候的一样的吗，去掉空格等

现在遇到问题，在手机支付后，对于支付宝发送的异步通知的sign无法匹配，我看源码是用公钥进行校验的
