### ISSUE TITLE
Alipay_WapExpress如何提交自定义参数并且异步的页面如何接收？

### ISSUE THREAD

**Issue by greatxj** [lokielse/omnipay-alipay#30]
Alipay_WapExpress如何提交自定义参数并且异步的页面如何接收？

**Comment by lokielse** [comment]
你好，之前的版本不支持这个特性。经过你的提醒，我刚提交了一个新版本`1.4.8`，请更新后测试

参照例子 https://github.com/lokielse/omnipay-alipay-example

```php
//请求订单需额外设置
$data = array(['foo'=>'bar']);
$extra = json_encode($data);
$gateway->setExtraCommonParam($extra);
```

```php
//支付完成后可通过支付宝的请求参数获取到`extra_common_param`参数
$extra = $_REQUEST['extra_common_param'];
$data = json_decode($extra);
```

**Comment by greatxj** [comment]
$gateway = \Omnipay::gateway ();
    $options['request_params'] = \Request::all();
    $options['sign_type']      = 'RSA';
    $options['ali_public_key']   =
config_path('alipay_key/alipay_public_key.pem');
    $response                   = $gateway->completePurchase($options)->send();

报错如下
ErrorException in ExpressCompletePurchaseRequest.php line 297:
openssl_verify(): supplied key param cannot be coerced into a public key
in ExpressCompletePurchaseRequest.php line 297
at HandleExceptions->handleError('2', 'openssl_verify(): supplied key param
cannot be coerced into a public key',


大神 方便加我QQ吗？244065504
