### ISSUE TITLE
同步验证的时候报错bug

### ISSUE THREAD

**Issue by greatxj** [lokielse/omnipay-alipay#32]
$gateway = \Omnipay::gateway ();
		$options['request_params'] = \Request::all();
		$options['sign_type']      = 'RSA';
		$options['ali_public_key']   = config_path('alipay_key/alipay_public_key.pem');
		$response                   = $gateway->completePurchase($options)->send();
报错如下
ErrorException in ExpressCompletePurchaseRequest.php line 297:
openssl_verify(): supplied key param cannot be coerced into a public key
in ExpressCompletePurchaseRequest.php line 297
at HandleExceptions->handleError('2', 'openssl_verify(): supplied key param cannot be coerced into a public key',

**Comment by lokielse** [comment]
请提供一下`config_path('alipay_key/alipay_public_key.pem')`返回的值

**Comment by greatxj** [comment]
请问支付宝提供的一长串的支付宝密钥字符串比如abcdefg如何转换成公钥pem格式的？
