### ISSUE TITLE
setService方法貌似不工作

### ISSUE THREAD

**Issue by orvice** [lokielse/omnipay-alipay#38]
Hi,

```
$gateway = Omnipay::create("Alipay_Express");
....
$gateway->setService("create_forex_trade");
```
我这样设置来使用国际版本，但是发起支付请求后，支付宝会返回如下的错误信息：

```
错误代码 ILLEGAL_PARTNER_EXTERFACE
```

如果将文件 ` https://github.com/lokielse/omnipay-alipay/blob/master/src/ExpressGateway.php` 
的  ` protected $service = 'create_direct_pay_by_user'; `

改成 ` protected $service = 'create_forex_trade'; `

就可以工作了。所以请问下，设置国际版的正确姿势是什么呢?

**Comment by lokielse** [comment]
@orvice 正确姿势 https://github.com/lokielse/omnipay-global-alipay

**Comment by orvice** [comment]
@lokielse 感谢回复.  试了下`omnipay-global-alipay`包OK了...

其实是因为昨天用global有问题所以才试试看这个包... 今天不知道为什么global包又可以了...
