### ISSUE TITLE
Alipay_WapExpress 支付成功的情况下异步返回后没有验证

### ISSUE THREAD

**Issue by vanrhy** [lokielse/omnipay-alipay#40]
"verify_success"和"is_paid"一直都是false

**Comment by lokielse** [comment]
请打开这个文件 https://github.com/lokielse/omnipay-alipay/blob/master/src/Message/ExpressCompletePurchaseRequest.php
203行，在此方法里面输出一下日志自行调试一下。

**Comment by vanrhy** [comment]
谢谢
好了
是公钥没配置好,用的开发者的,应该用支付宝公钥.
