### ISSUE TITLE
同步验证的生活一直报  Only scalar values are allowed for parameters

### ISSUE THREAD

**Issue by hongliming** [lokielse/omnipay-alipay#42]
错误信息： Only scalar values are allowed for parameters
 
调用：
`$options = [
    'request_params'=> array_merge($_POST, $_GET), //Don't use $_REQUEST for may contain $_COOKIE
];

$response = $gateway->completePurchase($options)->send();`
怎么破呢？是文档没更新么？

错误发生类：vendor/omnipay/common/src/Omnipay/Common/Message/AbstractRequest.php
 ` protected function setParameter($key, $value)
    {
        if (null !== $this->response) {
            throw new RuntimeException('Request cannot be modified after it has been sent!');
        }

        if (null !== $value && !is_scalar($value)) {
            throw new RuntimeException('Only scalar values are allowed for parameters');
        }

        $this->parameters->set($key, $value);

        return $this;
    }`

**Comment by lokielse** [comment]
请你把`$value`的值提供一下

**Comment by hongliming** [comment]
使用稳定版没问题了。使用开发有问题的。应该是与omnipay-common不同步导致。谢谢
