### ISSUE TITLE
建议支付宝手机web支付增加参数  "app_pay" => "Y",

### ISSUE THREAD

**Issue by hongliming** [lokielse/omnipay-alipay#43]
建议支付宝手机web支付增加参数  "app_pay" => "Y",
lokielse/omnipay-alipay/src/Message/WapExpressPurchaseRequest.php
`
$data = array(
            "service" => $this->getService(),
            "partner" => $this->getPartner(),
            "seller_id" => $this->getPartner(),
            "payment_type" => $this->getPaymentType(),
            "notify_url" => $this->getNotifyUrl(),
            "return_url" => $this->getReturnUrl(),
            "out_trade_no" => $this->getOutTradeNo(),
            "subject" => $this->getSubject(),
            "total_fee" => $this->getTotalFee(),
            "show_url" => $this->getShowUrl(),
            "body" => $this->getBody(),
            "it_b_pay" => $this->getItBPay(),
            "extern_token" => $this->getToken(),
            "_input_charset" => $this->getInputCharset(),
            "app_pay" => "Y",
        );
`
如此可以在移动端有更好的体验。调用已有的App支付

**Comment by hongliming** [comment]
https://doc.open.alipay.com/doc2/detail.htm?spm=a219a.7629140.0.0.HEXftc&treeId=60&articleId=104790&docType=1

**Comment by lokielse** [comment]
已加，请测试。

**Comment by hongliming** [comment]
已测试，感谢
