### ISSUE TITLE
怎么样添加业务请求参数的集合？

### ISSUE THREAD

**Issue by eleven0220** [lokielse/omnipay-alipay#46]
怎么样添加业务请求参数的集合 biz_content ？

**Comment by lokielse** [comment]
@eleven0220 目前暂不支持新版本的接口


如果你使用的是PC版快捷支付， 你可以使用`extra_common_param`参数设置自定义参数(字符串)

如果你使用的是移动端快捷支付，官方接口不支持自定义参数的传递，建议你在本地数据库存储与订单有关的数据。

**Comment by lokielse** [comment]
晚点我看下新接口，重构一下工程
