### ISSUE TITLE
可否升级新版API

### ISSUE THREAD

**Issue by janfon0715** [lokielse/omnipay-alipay#47]
支付宝推出新版API，希望予以更新和支持
[https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.Q1OqcK&treeId=193&articleId=105297&docType=1](https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.Q1OqcK&treeId=193&articleId=105297&docType=1)

[https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.6ckNlT&treeId=193&articleId=105285&docType=1](https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.6ckNlT&treeId=193&articleId=105285&docType=1)

**Comment by lokielse** [comment]
新版API还不完善，日后再支持。
