### ISSUE TITLE
 Fatal error: Cannot redeclare array_get() (previously declared in /src/Illuminate/Support/helpers.php:182)

### ISSUE THREAD

**Issue by Germey** [lokielse/omnipay-alipay#50]
Fatal error: Cannot redeclare array_get() (previously declared in /private/var/www/hwby/vendor/laravel/framework/src/Illuminate/Support/helpers.php:182) in /private/var/www/hwby/vendor/lokielse/omnipay-alipay/src/Common/helpers.php on line 32
PHP Fatal error:  Cannot redeclare array_get() (previously declared in /private/var/www/hwby/vendor/laravel/framework/src/Illuminate/Support/helpers.php:182) in /private/var/www/hwby/vendor/lokielse/omnipay-alipay/src/Common/helpers.php on line 32

Please add `function_exists` function in helpers.php.

**Comment by lokielse** [comment]
fix
