### ISSUE TITLE
file://引起的openssl错误

### ISSUE THREAD

**Issue by vanrhy** [lokielse/omnipay-alipay#51]
前几天一个服务器出现了openssl_sign(): supplied key param cannot be coerced into a private key的错误,追溯到源码里面文件是用file://打开的 于是改用fopen打开文件就OK了，不知道是什么原因引起的。

**Comment by lokielse** [comment]
请问是什么系统？方便提供一下PHP_OS的值吗

**Comment by vanrhy** [comment]
操作系统是Centos6.5 内核2.6.32-431.23.3.el6.x86_64 
PHP是7.0.2
apapce 2.4

**Comment by lokielse** [comment]
请在目标环境上测试一下, 下面3段代码是否都能正常执行
```php
<?php  //代码1

$key = '/the-absolute-path-of/your-private-key.pem';

if (strtoupper(substr(PHP_OS, 0, 3)) != 'WIN' && is_file($key) && substr($key, 0, 7) != 'file://') {
    $key = 'file://' . $key;
}

$res        = openssl_pkey_get_private($key);
openssl_sign('test', $sign, $res);
openssl_free_key($res);
$sign = base64_encode($sign);
```

```php
<?php  //代码2

$key = '/the-absolute-path-of/your-private-key.pem';
$key = file_get_contents($key);

if (strtoupper(substr(PHP_OS, 0, 3)) != 'WIN' && is_file($key) && substr($key, 0, 7) != 'file://') {
    $key = 'file://' . $key;
}

$res        = openssl_pkey_get_private($key);
openssl_sign('test', $sign, $res);
openssl_free_key($res);
$sign = base64_encode($sign);
```

```php
<?php  //代码3

$key = '/the-absolute-path-of/your-private-key.pem';
$fh  = fopen($key, 'r');
$key = fread($fh, 8192);
fclose($fh);

if (strtoupper(substr(PHP_OS, 0, 3)) != 'WIN' && is_file($key) && substr($key, 0, 7) != 'file://') {
    $key = 'file://' . $key;
}

$res        = openssl_pkey_get_private($key);
openssl_sign('test', $sign, $res);
openssl_free_key($res);
$sign = base64_encode($sign);
```

**Comment by vanrhy** [comment]
第二和第三段代码OK
第一段代码不行openssl_pkey_get_private始终返回的是false

**Comment by lokielse** [comment]
根据官方的文档 http://php.net/manual/en/function.openssl-pkey-get-private.php 

`openssl_pkey_get_private($key)` 这个`$key`可以是以下两种形式

- a string having the format `file://path/to/file.pem`. The named file must contain a PEM encoded certificate/private key (it may contain both).
- A PEM formatted private key.

按理说第一段代码应该也是没问题的，你能把第一段代码中的`$res        = openssl_pkey_get_private($key);` 参数`$key`的值打印出来吗？

**Comment by vanrhy** [comment]
发现问题了
要用服务器路径

但是这样是不是不太好，还是倾向于相对路径

**Comment by lokielse** [comment]
如果你用相对路径，第二，三段代码也无法执行的吧？？莫非你用的是URL?

**Comment by vanrhy** [comment]
没有啊
`<?php  //代码3

$key = 'the-absolute-path-of/your-private-key.pem';
`
the-absolute-path-of和代码在同一级目录

**Comment by lokielse** [comment]
哦，对的，那你改成绝对路劲, 大多数情况下，用绝对路劲要好一点。

相对路劲毕竟是执行的时候才能知道如何相对的。往往是配置单独放一个文件，多处都可能用到这个配置里面的路劲，如果用相对路劲，就会出错了。

**Comment by vanrhy** [comment]
嗯 好的 谢了
