### ISSUE TITLE
支付宝即时到账为什么变成legacy了

### ISSUE THREAD

**Issue by argb** [lokielse/omnipay-alipay#52]
支付宝即时到账为什么变成legacy了？
我看你的文档里都加了legacy,去蚂蚁金服网站看了下列出的四种支付服务也没有“即时到账”了，是不是以后就不支持pc网页支付了，如果不用即时到账服务怎么用支付宝进行pc网页的支付？

**Comment by lokielse** [comment]
支付宝做了一个新版的接口，但是及时到账还没出新版接口。为了区分，新版的接口都加了Aop前缀，老板的接口都加了Legacy前缀

你可以用新版SDK中的 `Alipay_LegacyExpress`
或者用[遗留版本](https://github.com/lokielse/omnipay-alipay/tree/legacy)中`Alipay_Express`

**Comment by argb** [comment]
就说即时到账的新版接口只是阿里巴巴还没放出来，不是废弃了，后面做好了就有了，对吧？
我还以为是阿里打算以后不支持pc网页支付了。

**Comment by lokielse** [comment]
是的

**Comment by argb** [comment]
ok 多谢解答

**Comment by lokielse** [comment]
Alipay Open Platform 支付宝开放平台
也是借用支付宝提供的SDK的命名空间

**Comment by argb** [comment]
明白了多谢，他们新版的即时到账有说什么时候可以用吗？

**Comment by lokielse** [comment]
这个不清楚

**Comment by kylesean** [comment]
@lokielse 作者您好，老版本的网银支付接口，更新之后，您现在这个版本里貌似没有了，刚接触支付宝的相关接口，更新较多，命名差异也大，一时有些糊涂。望提示下，感谢！
