### ISSUE TITLE
为什么新的app支付发起返回的sign是空

### ISSUE THREAD

**Issue by tradzero** [lokielse/omnipay-alipay#53]
![image](https://cloud.githubusercontent.com/assets/13845447/19263771/8b5d2cd4-8fd0-11e6-9921-38fda7509eee.png)
如图所示
notify_url是因为想先测试 没有放到公网上 所以随便用的
主要是不知道app私钥是直接读取pem文件还是只要除掉开始的-----BEGIN PUBLIC KEY-----

**Comment by lokielse** [comment]
用`$response->getOrderString()`获取订单字符串，该字符串直接用于客户端SDK调用支付服务

```php
$request = $gateway->purchase();
$request->setBizContent([
    'subject'      => 'test',
    'out_trade_no' => date('YmdHis') . mt_rand(1000, 9999),
    'total_amount' => '0.01',
    'product_code' => 'QUICK_MSECURITY_PAY',
]);

/**
 * @var AopTradeAppPayResponse $response
 */
$response = $request->send();

$response->getOrderString();
```

**Comment by lokielse** [comment]
https://github.com/lokielse/omnipay-alipay/wiki/Aop-APP-Gateway

**Comment by lokielse** [comment]
关于私钥格式问题见 https://github.com/lokielse/omnipay-alipay/wiki/FAQ

**Comment by tradzero** [comment]
@lokielse 非常感谢!
