### ISSUE TITLE
手机端支付宝支付问题，

### ISSUE THREAD

**Issue by huangkuan123** [lokielse/omnipay-alipay#54]
您好，openssl_sign(): supplied key param cannot be coerced into a private key。报这个错误，vendor\lokielse\omnipay-alipay\src\Common\Signer.php',这是什么问题啊？是有更新吗？

**Comment by lokielse** [comment]
私钥有问题，请检查

1. 私钥路劲是否正确（需使用绝对路劲）
2. 私钥的格式是否正确

**Comment by lokielse** [comment]
#51

**Comment by huangkuan123** [comment]
我的流程是这样的，把下载下来的rsa_private_key这个文件保存在当前文件夹中，然后用的$gateway->setPrivateKey('这里填写的是路径');是不是使用姿势不对啊？

**Comment by lokielse** [comment]
可以的，详见 https://github.com/lokielse/omnipay-alipay/wiki/FAQ

**Comment by huangkuan123** [comment]
我的秘钥路径没写好，现在秘钥通过了，在您文档中支付宝即时到账接口的$response->getRedirectUrl();使用这个方法会返回一个空白页面，使用redirect是正常的，在手机端使用这个函数会报错，这个方法未定义，在微信扫码支付中的回调里，Omnipay::create使用这个create，回调方法下面的均未执行，应该是错误了，用gateway没问题，我感觉我还是哪里没搞好，有其他人出现过这问题吗？

**Comment by lokielse** [comment]
`$response->getRedirectUrl();` 方法会返回一个字符串，即跳转链接。

**Comment by lokielse** [comment]
手机网页支付`AopTradeWapPayResponse` 和 PC支付`LegacyExpressPurchaseResponse`都实现了`RedirectResponseInterface`协议，不存在你说的`redirect`方法不存在的问题哈，请自行检查是否存在拼写错误。

**Comment by lokielse** [comment]
微信扫码支付？？
