### ISSUE TITLE
支付宝APP支付回调函数逻辑不通

### ISSUE THREAD

**Issue by xlkit456852** [lokielse/omnipay-alipay#58]
代码如下：
`
Log::info('Alipay Notify request arrived.');
		$gateway = Omnipay::create('Alipay_AopApp');
		$gateway->setAppId('xxxxxx');
		$gateway->setPrivateKey(File::get('../config/key/alipay/private_key.pem'));
		$gateway->setAlipayPublicKey(File::get('../config/key/alipay/public_key.pem'));
		$gateway->setNotifyUrl(NOTIFY_DOMAIN.'alipayNotify');

		Log::info('Alipay Notify gateway: '.json_encode($gateway));

		$request = $gateway->completePurchase();

		Log::info('Alipay Notify request: '.json_encode($request));
		
		$request->setParams($_POST);//Optional

		try {
			$response = $request->send();

			if($response->isPaid()){

				Log::info('Alipay Notify isPaid.'.json_encode($_POST));

				//支付成功，处理订单
				die($this->handle_order_success($sheet,$trade_no,1));
			}else{
				/**
				 * Payment is not successful
				 */
				die($this->alipayNotifyReturnfalse);
			}
		} catch (\Exception $e) {
			/**
			 * Payment is not successful
			 */
			die($this->alipayNotifyReturnfalse);
		}
`
支付已经成功，也已经进入了这个notify回调函数，但使用日志打印出$gateway和$request都为空，而且也无法进入$respoinse->isPaid()的判断里。但$_POST中已经有支付宝返回的所有成功数据，这里的不是很明白编写者的意图。

**Comment by lokielse** [comment]
1. 关于意图：支付成功异步回调的**意图**就是异步通知服务端订单支付成功了！异步验证不是必须的，但是这个是相比客户端验证支付状态而言更加安全的做法。

2. 关于调试方法的建议，建议你看看`error_log`。根据你说的无法进入`$respoinse->isPaid()`, 那么就很有可能在`$response = $request->send();`中发生了异常， 但是你的`catch`方法中并没有记录异常，而是直接`die`了。

3. 关于`$gateway`和`$request`为空，这个可能是你的日志打印程序有问题，`Omnipay::create('Alipay_AopApp')`返回的实例永远都是不为空的，如果`Alipay_AopApp`这个网关不存在，那么会抛出异常，也不存在返回对象这个事情了。

4. 关于APP支付测试的例子，见[这里](https://github.com/lokielse/omnipay-alipay/blob/master/tests/AopAppGatewayTest.php), 所有的方法都是通过的。

所以建议你看看`error_log`，把异常信息找明确了再上来提`issue`

**Comment by lokielse** [comment]
`Log::info('Alipay Notify gateway: '.json_encode($gateway));`这个打印结果应该如下，这是正常的，不是说明它为空

```
Alipay Notify gateway: {}
```

你需改成`Log::info('Alipay Notify gateway: '.serialize($gateway));`

**Comment by xlkit456852** [comment]
的确是catch出异常了，异常信息是“The publicKey is invalid  ”，但发起支付和这个回调都是用同一个publicKey的，怎么就非法了？

**Comment by lokielse** [comment]
创建订单是不需要支付宝公钥，所以不会报异常。
