### ISSUE TITLE
支付宝APP支付回调抛出公钥不合法的异常

### ISSUE THREAD

**Issue by xlkit456852** [lokielse/omnipay-alipay#59]
给予前端预付参数：
`
$gateway = Omnipay::create('Alipay_AopApp');
		$gateway->setAppId('xxxxxxx');
		$gateway->setPrivateKey(config_path('key/alipay/private_key.pem'));
		$gateway->setAlipayPublicKey(config_path('key/alipay/public_key.pem'));
		$gateway->setNotifyUrl(NOTIFY_DOMAIN.'alipayNotify');

		$request = $gateway->purchase();
		$request->setBizContent([
			'subject'      => '商品',
			'out_trade_no' => $sheet->sheetNumber,
			'total_amount' => $sheet->money,
			'product_code' => 'QUICK_MSECURITY_PAY',

		]);

		/**
		 * @var AopTradeAppPayResponse $response
		 */
		$response = $request->send();

		$orderString = $response->getOrderString();
`
支付回调Notify：
`
$gateway = Omnipay::create('Alipay_AopApp');
		$gateway->setAppId('xxxxxxxx');
		$gateway->setPrivateKey(config_path('key/alipay/private_key.pem'));
		$gateway->setAlipayPublicKey(config_path('key/alipay/public_key.pem'));
		$gateway->setNotifyUrl(NOTIFY_DOMAIN.'alipayNotify');

		$request = $gateway->completePurchase();
		$request->setParams($_POST);//Optional
		try {
			$response = $request->send();
			if($response->isPaid()){
	
				//支付成功，处理订单
				die($this->handle_order_success($sheet,$trade_no,1));
			}else{
				/**
				 * Payment is not successful
				 */
				die($this->alipayNotifyReturnfalse);
			}
		} catch (\Exception $e) {
			/**
			 * Payment is not successful
			 */
			Log::info('Alipay Notify catch fail.'.$e->getMessage());
			//die($this->alipayNotifyReturnfalse);
		}
`

回调函数抛出了异常，异常信息是“The publicKey is invalid  ”，公钥不合法，不知道是不是setAlipayPublicKey方法传的内容不正确？但我试过传路径、传一行公钥字符串进去，均抛出上面的异常。暂未找到解决方法。。。

**Comment by xlkit456852** [comment]
另外我用的公钥也是“支付宝公钥”，不是“应用公钥”

**Comment by lokielse** [comment]
见 wiki - FAQs

**Comment by liuwz465501235** [comment]
我也出现了这种情况！！你给一个FAQs地址我去看看啊？？？？

**Comment by xlkit456852** [comment]
https://github.com/lokielse/omnipay-alipay/wiki/FAQs 兄弟，这里。
