### ISSUE TITLE
notify_url 生成错误

### ISSUE THREAD

**Issue by breeze-liu** [lokielse/omnipay-alipay#60]
laravel 日志查询支付宝不访问我的回调notify_url , 而自己通过post 模拟数据是可以访问的, 服务确认是外网, 查看返回的getOrderString(仅url部分)如下

notify_url=https%3A%2F%2Fapi.xxxxxxx.com%2Falipay%2Fnotify&sign_type=RSA&timestamp=2016-11-15+17%3A23%3A14&version=1.0&sign=WYN%2BEq22Q%2B0FT3o67wwfneFn8Ds2jBY71Nm41FJUnxTgL7xGd%2BSEo0u0u3Tvp57noB6z7hXcT23kwDPAwHEU45W%2Fs2lCR1MdeEZ22cxpzy%2BrFPBNeKpcOnyhRvdTDWWeeZY0z02EBLUA%2F%2F5iv4aA3np8tq9uC9Rt8UhAUcd%2FwjA%3D

decode后:
notify_url=https://api.xxxxxxx.com/alipay/notify&sign_type=RSA&timestamp=2016-11-15 17:23:14&version=1.0&sign=WYN+Eq22Q+0FT3o67wwfneFn8Ds2jBY71Nm41FJUnxTgL7xGd+SEo0u0u3Tvp57noB6z7hXcT23kwDPAwHEU45W/s2lCR1MdeEZ22cxpzy+rFPBNeKpcOnyhRvdTDWWeeZY0z02EBLUA//5iv4aA3np8tq9uC9Rt8UhAUcd/wjA=

这里
https://api.xxxxxx.com/alipay/notify 是我的notify_url 而后面跟的第一个参数是以&开始而不是以?开始, 测试下, 发现无法访问, 而换成?号可以访问, 所以是不是因为这个原因导致支付宝不访问我的回调地址

将notify_url手动添加一个预置参数 https://api.xxxxxx.com/alipay/notify?ex=0, 发现无法调用支付宝, 猜想与sign有关, 无耐不解, 希望帮助, 谢谢

**Comment by lokielse** [comment]
decode只需要对 `https%3A%2F%2Fapi.xxxxxxx.com%2Falipay%2Fnotify` 进行decode, 所以这个值是没问题的

我看你用的是`https`, 估计你是用的`Let's Encrypt`?? 支付宝目前不支持`Let's Encrypt`

**Comment by breeze-liu** [comment]
Let's Encrypt ? 搜了下是ssls提供商吗, 我们用的不是这家的, 是comodo 的ov证书

**Comment by breeze-liu** [comment]
谢谢提醒, 将url 改http 支付宝确实可以回调了, 难道它不支付https?

**Comment by lokielse** [comment]
有些https证书是不支持的，这个你可以和支付宝那边确认一下。

**Comment by breeze-liu** [comment]
谢谢
