### ISSUE TITLE
为什么项目的文件都用ANSI,不用UTF8?

### ISSUE THREAD

**Issue by cenchy** [lokielse/omnipay-alipay#61]
![image](https://cloud.githubusercontent.com/assets/11435955/20511973/85db86c2-b0b7-11e6-9be8-87a19e528f8c.png)
UTF8项目,引用后出点问题了

**Comment by lokielse** [comment]
<img width="253" alt="qq20161122-0 2x" src="https://cloud.githubusercontent.com/assets/1573211/20516034/5c5e451a-b0cf-11e6-81df-15dc0e7ed02f.png">
是UTF-8呀，你的IDE有问题吧
