### ISSUE TITLE
AopTradeRefundRequest 的 response

### ISSUE THREAD

**Issue by liyu001989** [lokielse/omnipay-alipay#62]
Requests/AopTradeRefundRequest.php 的 sendData 应该实例化 AopTradeRefundResponse 

这样最后的isSuccessful才对

**Comment by lokielse** [comment]
@liyu001989 已修复

**Comment by liyu001989** [comment]
👍 好快啊

**Comment by liyu001989** [comment]
tag 好像点问题，现在有个 `2.0.5`，`2.0.6`  和`v2.0.5`    composer 现在默认到了 2.0.6 更新不了刚才的bug了。

 `2.0.5`，`2.0.6`  这两个分支是什么情况啊，是不是该删了

**Comment by lokielse** [comment]
现在把2.0.5，2.0.6删掉了，你重新搞一下吧

**Comment by liyu001989** [comment]
还是不对
好像是 packagist 没有同步， 还有个2.0.6

**Comment by lokielse** [comment]
刚重新发了一个`v2.0.7`

**Comment by liyu001989** [comment]
okok   对了  ，感谢
