### ISSUE TITLE
您好。不能安装这个包。这个包是否需要其他包支持呢？

### ISSUE THREAD

**Issue by gaodeyang** [lokielse/omnipay-alipay#63]
`root@iZ25ruznwssZ:/data/www/hnair_four# composer require lokielse/omnipay-alipay
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^2.0 for lokielse/omnipay-alipay
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.7
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.5
    - lokielse/omnipay-alipay v2.0.4 requires omnipay/common ~2.5.1 -> satisfiable by omnipay/common[v2.5.1].
    - Conclusion: don't install omnipay/common v2.5.1
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.3
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.2
    - Conclusion: don't install lokielse/omnipay-alipay v2.0.1
    - Conclusion: remove symfony/event-dispatcher v3.1.3
    - Conclusion: don't install symfony/event-dispatcher v3.1.3
    - omnipay/common 2.4.0 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - omnipay/common v2.3.4 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - omnipay/common v2.4.1 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].
    - omnipay/common v2.5.0 requires guzzle/guzzle ~3.9 -> satisfiable by guzzle/guzzle[v3.9.0, v3.9.1, v3.9.2, v3.9.3].

**Comment by lokielse** [comment]
```
 composer update lokielse/omnipay-alipay
```

**Comment by gaodeyang** [comment]
我也试了这种方式。但是没有还是没有生效。

**Comment by gaodeyang** [comment]
Package "lokielse/omnipay-alipay" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader

**Comment by lokielse** [comment]
#56 你看看这个，

**Comment by lokielse** [comment]
把 `composer.lock`和`vendor`删了再试一试，不行的话你具体看报错的信息，就是依赖方面导致的问题。

**Comment by lokielse** [comment]
建议你使用 [中国镜像](http://pkg.phpcomposer.com/) 来加速安装

**Comment by gaodeyang** [comment]
谢谢  我先试下。
