### ISSUE TITLE
app支付2.0，orderString多出来个alipay_sdk参数，导致APP端调用支付ALI40247

### ISSUE THREAD

**Issue by weibocy** [lokielse/omnipay-alipay#64]
> 发起支付宝支付OK，回应orderString：alipay_sdk=lokielse%2Fomnipay-alipay&app_id=2016103002419260&biz_content=%7B%22subject%22%3A%22%5Cu4f59%5Cu989d%5Cu5145%5Cu503c%5B201612011342592526%5D%22%2C%22out_trade_no%22%3A%22201612011342592526%22%2C%22total_amount%22%3A%220.01%22%2C%22product_code%22%3A%22QUICK_MSECURITY_PAY%22%2C%22passback_params%22%3A%22recharge_id%3D27%22%7D&charset=UTF-8&format=JSON&method=alipay.trade.app.pay&notify_url=http%3A%2F%2Fwww.guoshuzc.com%2Fapi%2Fpay%2Falipay_recharge_notify&sign_type=RSA&timestamp=2016-12-01+13%3A42%3A59&version=1.0&sign=O3fQSinspo84kXcsuMAytFwUuC%2BlCM%2FgxF49Ylx1mLRUhFYyHeeSCFcy8wvpQGTuqtk0o7GLYoA4WVObF0HZAl4fl2dFues8bDU4imPNZR%2FVDO4sEQYkU2%2FBsNR0TdZDfihBC75X1oVd5ehH6EfFAI7ZPBEVwD83AX2PjAORrJo%3D

以上是orderString，这个地方多出来了alipay_sdk参数，请问是否是这个原因导致的？谢谢

另外贴出我的代码

>  $this->alipay_gateway = Omnipay::create(config('pay.alipay.alipay_gateway'));
>             $this->alipay_gateway->setAppId(config('pay.alipay.app_id')); // APPID
>             $this->alipay_gateway->setPrivateKey(config('pay.alipay.app_private_key'));
> //            $this->alipay_gateway->setAlipayPublicKey(config('pay.alipay.alipay_public_key'));

 // 设置付款通知地址

>             $this->alipay_gateway->setNotifyUrl('http://' . $_SERVER['HTTP_HOST'] . '/api/pay/alipay_recharge_notify');
>             $pay_request = $this->alipay_gateway->purchase();

> $pay_request->setBizContent([
>                 'subject'      => '余额充值['. $out_trade_no .']',
>                 'out_trade_no' => $out_trade_no,
>                 'total_amount' => $user_recharge->recharge_moneys,
>                 'product_code' => 'QUICK_MSECURITY_PAY',
>                 'passback_params' =>  'recharge_id=' . $recharge_id,
>             ]);

  //发起支付
 

>        try{
>             $response = $pay_request->send();
>             $orderString = $response->getOrderString();
>             Log::DEBUG("发起支付宝支付OK，回应orderString：". $orderString);
>             return ajaxMessage(false, '发起付款成功', ['orderString'=>$orderString]);
>         }catch (\Exception $e){
>             Log::DEBUG($e->getMessage());
>         }
>         return ajaxMessage(false, '发起付款失败', ['orderString'=>-1]);

**Comment by lokielse** [comment]
应该不是，我之前测试过的，是OK的。

验证方法也很简单，你到代码里面去把alipay_sdk那一行注释掉就行了。

**Comment by weibocy** [comment]
会不会是我证书加载方式有问题？

**Comment by lokielse** [comment]
我也不清楚，你最好从头检查一下每个细节问题，比如是否签约响应产品、重新生成一下证书、检查KEY等等

另外保证你的客户端的包名和签约是一致的，不要搞个`com.example.alipay`就来测试了。。。

除此之外，使用本SDK生产的订单字符串不要`ctrl+c`,`ctrl+v`拷贝到你的客户端工程里面来测试，因为有些IDE会自动把你粘贴进去的字符串做转义，可能就会产生问题，最好做一个接口，调用接口返回订单，然后将变量进行传参数。

**Comment by gxfunc** [comment]
您好，请问有打印参数的方法吗？我这边想做签名验证

**Comment by lokielse** [comment]
@gxfunc 
```php
var_dump($response->getData());
```

**Comment by lokielse** [comment]
@weibocy 我仔细看了下你的订单字符串，发现`subject`中包含了订单号，这是不允许的。

**Comment by lokielse** [comment]
@weibocy 你把`passback_params`移除试一试

**Comment by lokielse** [comment]
@weibocy 根据支付宝的文档, `passback_params`参数需要做`urlencode`

https://doc.open.alipay.com/docs/doc.htm?treeId=193&articleId=105465&docType=1

**Comment by gxfunc** [comment]
您好回应的data 是这样的

lokielse/omnipay-alipay2016103002419260{"subject":"\u4ea7\u5730\u76f4\u4f9b\u6c34\u679c\u8ba2\u5355","out_trade_no":"201612301726368120","total_amount":"80.00","product_code":"QUICK_MSECURITY_PAY","passback_params":"order_id=363"}UTF-8JSONalipay.trade.app.payhttp://www.guoshuzc.com/api/pay/alipay_shop_notifyRSA2016-12-30 17:40:511.05a7 SDlnq1thdTCurBmWjhdTxe4XNrXM6ahqaQCsnU05bEoU0VcaXiEdx1hjY5Pxa2WIAiI1gGNBJHuvL8LWvOIaZBgzsuuudhWVRPTXXA5ik/XdUpgMXU8TUhkngjC6hGEGiYzApCALUXVJNUnbXK xkTacgwChRjzSoRJgeWQ=alipay_sdk=lokielse/omnipay-alipay

app_id=2016103002419260

biz_content={"subject":"\u4ea7\u5730\u76f4\u4f9b\u6c34\u679c\u8ba2\u5355","out_trade_no":"201612301726368120","total_amount":"80.00","product_code":"QUICK_MSECURITY_PAY","passback_params":"order_id=363"}

charset=UTF-8

format=JSON

method=alipay.trade.app.pay

notify_url=http://www.guoshuzc.com/api/pay/alipay_shop_notify

sign_type=RSA

timestamp=2016-12-30 17:40:51

version=1.0

sign=5a7+SDlnq1thdTCurBmWjhdTxe4XNrXM6ahqaQCsnU05bEoU0VcaXiEdx1hjY5Pxa2WIAiI1gGNBJHuvL8LWvOIaZBgzsuuudhWVRPTXXA5ik/XdUpgMXU8TUhkngjC6hGEGiYzApCALUXVJNUnbXK+xkTacgwChRjzSoRJgeWQ=


原样数据：
lokielse/omnipay-alipay2016103002419260{"subject":"\u4ea7\u5730\u76f4\u4f9b\u6c34\u679c\u8ba2\u5355","out_trade_no":"201612301726368120","total_amount":"80.00","product_code":"QUICK_MSECURITY_PAY","passback_params":"order_id=363"}UTF-8JSONalipay.trade.app.payhttp://www.guoshuzc.com/api/pay/alipay_shop_notifyRSA2016-12-30 17:40:511.05a7+SDlnq1thdTCurBmWjhdTxe4XNrXM6ahqaQCsnU05bEoU0VcaXiEdx1hjY5Pxa2WIAiI1gGNBJHuvL8LWvOIaZBgzsuuudhWVRPTXXA5ik/XdUpgMXU8TUhkngjC6hGEGiYzApCALUXVJNUnbXK+xkTacgwChRjzSoRJgeWQ=alipay_sdk=lokielse%2Fomnipay-alipay&app_id=2016103002419260&biz_content=%7B%22subject%22%3A%22%5Cu4ea7%5Cu5730%5Cu76f4%5Cu4f9b%5Cu6c34%5Cu679c%5Cu8ba2%5Cu5355%22%2C%22out_trade_no%22%3A%22201612301726368120%22%2C%22total_amount%22%3A%2280.00%22%2C%22product_code%22%3A%22QUICK_MSECURITY_PAY%22%2C%22passback_params%22%3A%22order_id%3D363%22%7D&charset=UTF-8&format=JSON&method=alipay.trade.app.pay&notify_url=http%3A%2F%2Fwww.guoshuzc.com%2Fapi%2Fpay%2Falipay_shop_notify&sign_type=RSA&timestamp=2016-12-30+17%3A40%3A51&version=1.0&sign=5a7%2BSDlnq1thdTCurBmWjhdTxe4XNrXM6ahqaQCsnU05bEoU0VcaXiEdx1hjY5Pxa2WIAiI1gGNBJHuvL8LWvOIaZBgzsuuudhWVRPTXXA5ik%2FXdUpgMXU8TUhkngjC6hGEGiYzApCALUXVJNUnbXK%2BxkTacgwChRjzSoRJgeWQ%3D

________________________________
weibocy@hotmail.com

发件人： Loki Else<mailto:notifications@github.com>
发送时间： 2016-12-30 16:34
收件人： lokielse/omnipay-alipay<mailto:omnipay-alipay@noreply.github.com>
抄送： gxfunc<mailto:weibocy@hotmail.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [lokielse/omnipay-alipay] app支付2.0，orderString多出来个alipay_sdk参数，导致APP端调用支付ALI40247 (#64)

@gxfunc<https://github.com/gxfunc>

var_dump($response->getData());

**Comment by lokielse** [comment]
```
$pay_request->setBizContent([
    'subject' => '余额充值['. $out_trade_no .']',
    'out_trade_no' => $out_trade_no,
    'total_amount' => $user_recharge->recharge_moneys,
    'product_code' => 'QUICK_MSECURITY_PAY',
    'passback_params' => urlencode('recharge_id=' . $recharge_id), //这里
]);
```

**Comment by lokielse** [comment]
@weibocy @gxfunc 你们为何要把订单号放在`passback_params`里面呢，`out_trade_no`就是商户订单号啊，你们自己没数据库的吗...

**Comment by gxfunc** [comment]
搞定了，非常感谢各位大神的帮助；

________________________________
weibocy@hotmail.com

发件人： Loki Else<mailto:notifications@github.com>
发送时间： 2016-12-30 17:46
收件人： lokielse/omnipay-alipay<mailto:omnipay-alipay@noreply.github.com>
抄送： gxfunc<mailto:weibocy@hotmail.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [lokielse/omnipay-alipay] APP端调用支付ALI40247 (#64)

$pay_request->setBizContent([
    'subject' => '余额充值['. $out_trade_no .']',
    'out_trade_no' => $out_trade_no,
    'total_amount' => $user_recharge->recharge_moneys,
    'product_code' => 'QUICK_MSECURITY_PAY',
    'passback_params' => urlencode('recharge_id=' . $recharge_id), //这里
]);

**Comment by gxfunc** [comment]
确实有点多余，不好意思啦，我新手，我现在是用out_trade_no + order_id 一起去数据库查的，

________________________________
weibocy@hotmail.com

发件人： Loki Else<mailto:notifications@github.com>
发送时间： 2016-12-30 17:51
收件人： lokielse/omnipay-alipay<mailto:omnipay-alipay@noreply.github.com>
抄送： gxfunc<mailto:weibocy@hotmail.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [lokielse/omnipay-alipay] APP端调用支付ALI40247 (#64)

@weibocy<https://github.com/weibocy> @gxfunc<https://github.com/gxfunc> 你们为何要把订单号放在passback_params里面呢，out_trade_no就是商户订单号啊，你们自己没数据库的吗...

**Comment by chzhm159** [comment]
求救,请相信我,以下操作已经做了N遍,仍然报错 ALI40247(这都是毫不费劲的敲出来的...)
通过 openssl生成公私钥
# 生成2048位私钥
genrsa -out rsa_private_key.pem   2048  
# 生成公钥
rsa -in rsa_private_key.pem -pubout -out rsa_public_key.pem

然后  去掉 -----BEGIN PUBLIC KEY----- 和 '-----END PUBLIC KEY-----',并且把剩下的内容变为一行,并删除了其中的换行符. 然后填写到支付宝管理页.

把私钥上传到了我们自己的网站中.这是返回的(sign的值和notify_url我做了删减,app_id,替换了)
`alipay_sdk=lokielse%2Fomnipay-alipay&app_id=xxxxx&biz_content=%7B%22subject%22%3A%22%5Cu8ba2%5Cu5355%5Cu652f%5Cu4ed8%22%2C%22out_trade_no%22%3A%22a6e11658b6c24a94ae5c7debd6ce8f9b%22%2C%22total_amount%22%3A%220.01%22%2C%22product_code%22%3A%22QUICK_MSECURITY_PAY%22%7D&charset=UTF-8&format=JSON&method=alipay.trade.app.pay&notify_url=https%3A%2F%2Fy.we.org%3A443%2Fv%2Fomnipay%2Fuse%2Falipay%2Fexpress%2Fnotify.json&sign_type=RSA2&timestamp=2017-03-10+18%3A38%3A06&version=1.0&sign=C%2B39%2FxOLvyLVyZoRdpXsbYLFtxtazjiDOupBefEsing4XjnXvtL3ap%2By00ArhUOK3KxVpfBI6MQyf7SkZGCS%2BXgCf7vBbEKIVb3Zz%2FM8fNM3z20ELxi2x%2Ba0ZN7c5zTdZMvXRoGVu50IFZbUTJAM6%2BX0CvxemvEqTHATKBtsTpJ3GhNFmQ5TJUvzJqKe6KTgLJbqs0GrELaHM90q0aqSEDT49XFgbjjfXEGajJ6f6%2FBVdZq%2Fi6KWGLaLAkBz%2F78d4u0hZrUqBv6%2BatRjfhQBWl%2F0rUQY94TYuQAICSmqHsQ%3D%3D`

我简单分组后的信息,便于查看
alipay_sdk=lokielse%2Fomnipay-alipay&

app_id=xxxxx&

biz_content=%7B%22subject%22%3A%22%5Cu8ba2%5Cu5355%5Cu652f%5Cu4ed8%22%2C%22out_trade_no%22%3A%22a6e11658b6c24a94ae5c7debd6ce8f9b%22%2C%22total_amount%22%3A%220.01%22%2C%22product_code%22%3A%22QUICK_MSECURITY_PAY%22%7D&

charset=UTF-8&

format=JSON&

method=alipay.trade.app.pay&

notify_url=https%3A%2F%2Fy.we.org%3A443%2Fv%2Fomnipay%2Fuse%2Falipay%2Fexpress%2Fnotify.json&

sign_type=RSA2&

timestamp=2017-03-10+18%3A38%3A06&

version=1.0&

sign=C%2B39%2FxOLvyLVyZoRdpXsbYLFtxtazjiDOupBefEsing4XjnXvtL3ap%2By00ArhUOK3KxVpfBI6MQyf7SkZGCS%2BXgCf7vBbEKIVb3Zz%2FM8fNM3z20ELxi2x%2Ba0ZN7c5zTdZMvXRoGVu50IFZbUTJAM6%2BX0CvxemvEqTHATKBtsTpJ3GhNFmQ5TJUvzJqKe6KTgLJbqs0GrELaHM90q0aqSEDT49XFgbjjfXEGajJ6f6%2FBVdZq%2Fi6KWGLaLAkBz%2F78d4u0hZrUqBv6%2BatRjfhQBWl%2F0rUQY94TYuQAICSmqHsQ%3D%3D

**Comment by lokielse** [comment]
你好，请在支付宝开发平台设置一个SHA1的密钥试一下，然后把sign_type设置为RSA。如果还是报这个错误的话可能你的账户没有相关权限哦。

**Comment by lokielse** [comment]
@chzhm159 另外请确认你使用的是正式环境。沙箱环境也会报这个错误的。

**Comment by chzhm159** [comment]
已经和支付宝客服确认过权限没有问题.而且也是正式环境. 那我再从客户端看看是不是客户端sdk的问题

**Comment by lokielse** [comment]
@chzhm159 请你用SHA1试一试，RSA2也是最近才搞出来的，还未广泛使用，半个月前一个人PR过来的。

**Comment by chzhm159** [comment]
谢谢了,几个原因纠缠在一起,导致一直找不到错误原因.我们的错误有多处,在这整理一下,方便后面遇到此类问题的朋友排查原因
* 1. 客户端是基于cordova构建的,支付宝支付用的是一个cordova的插件,而这个插件内置的支付宝sdk是2015年的版本. 首先我升级了支付宝sdk版本
* 2. 在初次排错的时候,根据支付宝文档,怀疑是 "alipay_sdk=lokielse%2Fomnipay-alipay" 这个多出来的参数导致的,所以服务器端返回订单信息后,我把这个参数给删除了,然后传递给客户端的. **那么服务器端生成的sign和支付宝验证时生成的sign肯定是不一致的**
* 3. 支付宝开放平台配置应用公钥的时候,其中包含换行符 **\n**
* 4. 我们的服务器后端配置的应用私钥也不是**pem**格式,而是用支付宝公私钥生成工具生成的.
* 5. 期间管理管理商户支付宝账号的同事,配置的一会是RSA一会是RSA2....也导致各种失败

**Comment by chzhm159** [comment]
* 1. 支付宝推荐使用RSA2,用这个是没问题的
* 2. 开放平台配置的时候,授权回调接口的验证方式务必要和所使用的加密方式统一.是RSA就选则RSA,是RSA2就选择RSA2
* 3. 应用的公私钥,推荐使用OpenSSL命令行工具生成,直接生成pem格式,而不是pkcs*的.
 `# 生成2048位私钥
genrsa -out rsa_private_key.pem   2048  
# 生成公钥
rsa -in rsa_private_key.pem -pubout -out rsa_public_key.pem`
生成的公钥需要处理,之后再进行应用公钥配置
处理过程: 去掉 -----BEGIN PUBLIC KEY----- 和 -----END PUBLIC KEY-----,并且剩余内容中的**\n**删除 : 或者执行命令： 
 `cat srcpemfile | sed '1d;$d' | tr -d '\n' > targetpemfile`
* 4.应用私钥直接上传到自己的服务器后台,支付宝公钥是直接用开放平台下载得到的txt文件即可. 这两个文件不需要额外处理
* 5.对于本库所返回的orderString中附带的"alipay_sdk=xxx"不可删除,保留即可,原封不动的传递个支付宝sdk支付接口
