### ISSUE TITLE
没有地方可以自定义默认参数和删除默认参数？

### ISSUE THREAD

**Issue by chinawilon** [lokielse/omnipay-alipay#69]
`public function getDefaultParameters()
   `{
       ` return [
            `'inputCharset' => 'UTF-8',
           ` 'signType'     => 'MD5',
            `'paymentType'  => '1',
            `'alipaySdk'    => 'lokielse/omnipay-alipay',
        `];
    }`

omnipay貌似无法删除已经注入的默认参数。希望作者提供一个入口可以自定义这些默认参数， 比如我想删除掉alipaySdk这个参数 [参数的确是可以在配置里面注入进入和覆盖或者通过setParameter，但是无法删除！], 要么就不要给默认参数， 全部由外部注入。

omnipay提供了一个setParameter方法， 作者为何不直接写个__call方法去设置这些请求参数。这样子的话，配置文件里面的参数也可以全部注入进去，而不需要依靠setter才能注入进去， 更加方便。

omnipay设计上貌似不能由外部重定义方法和属性，这样的话感觉不能适应可变化的sdk，第三方不可能实时的催作者去更新他的代码库吧。 总的来说，给自己用还差不多， 不适合给第三方使用。

**Comment by lokielse** [comment]
看到你说的这些问题，总的来说，给自己写写代码还差不多， 不适合使用使用第三方的代码。
