### ISSUE TITLE
您好！请问能有配置项的说明吗？

### ISSUE THREAD

**Issue by xianglong111** [lokielse/omnipay-alipay#70]
请问能有配置项的说明吗？比如说需要配置哪些地方？以及这些配置分别代表什么意思？ 
![qq 20161223171813](https://cloud.githubusercontent.com/assets/9738743/21450668/e27339d6-c933-11e6-9d0a-f05d2c86cdca.jpg)
非常感谢！

**Comment by ryh** [comment]
看文档好么？ 首页  [README.md](https://github.com/lokielse/omnipay-alipay/blob/master/README.md) LINKS里的Usage / Doc

RTFM!  check with the Usage / Doc in [README.md](https://github.com/lokielse/omnipay-alipay/blob/master/README.md)
--

@lokielse btw，seems that `ALIPAY_APP_ENCRYPT_KEY` was never used in the test

**Comment by lokielse** [comment]
@ryh 支付宝开放平台的接口中，有些接口会用到`AES`密钥，但是在支付方面的接口貌似暂时用不到这个`AES`密钥，但是还是留着了。
