### ISSUE TITLE
wrong  method: Omnipay::create('Alipay_LegacyExpress'); 类方法错误，

### ISSUE THREAD

**Issue by terrywamg** [lokielse/omnipay-alipay#72]
$gateway = Omnipay::create('Alipay_LegacyExpress');

[detail](https://github.com/lokielse/omnipay-alipay/wiki/Legacy-Express-Gateway)

这句代码无法运行，应该是文档需要更新了吧？有替代方法了吗？
the code does not run? I think the document should be updated. Is there new manual?

**Comment by lokielse** [comment]
请问你的`Omnipay`这个类的命名空间是什么？

**Comment by terrywamg** [comment]
我用的门面

use Omnipay;
class xxxx{
.....
function asdffas{
$gateway = Omnipay::create('Alipay_LegacyExpress');


}
...
}

**config.php 中：**
'providers' => [
...
 Ignited\LaravelOmnipay\LaravelOmnipayServiceProvider::class,
...
],

'aliases' => [
...
 'Omnipay' => Ignited\LaravelOmnipay\Facades\OmnipayFacade::class,
...
]

**Comment by lokielse** [comment]
如果你使用`laravel/omnipay` 请阅读它的[文档](https://github.com/ignited/laravel-omnipay)

首先你需要使用配置`config/laravel-omnipay.php`来创建一个支付配置

创建网关实例的方法是
```
$gateway = Omnipay::gateway('the_config_name');
```
而非
```
$gateway = Omnipay::create('Alipay_LegacyExpress');
```
