### ISSUE TITLE
您好，可否升级一下代码，关于guzzle/guzzle

### ISSUE THREAD

**Issue by kazegt** [lokielse/omnipay-alipay#73]
`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/gu
zzle instead.`

你好作者，我一直在用您的支付宝和微信支付的项目，做的非常实用，但本人有代码洁癖（估计用LAVAREL的人多数都和我一样），所以每次composer update的时候提示的这个让我很崩溃……哈哈，如果可以请麻烦把comnipay-common一起升级了，因为guzzle/guzzle主要是comnipay引用的，谢谢~哈哈

**Comment by lokielse** [comment]
爱莫能助，这个问题很早就有人讨论过了 https://github.com/thephpleague/omnipay/issues/235
