### ISSUE TITLE
即时到账支付成功后，不执行notify回调

### ISSUE THREAD

**Issue by rockleeyuetian** [lokielse/omnipay-alipay#78]
您好，我使用的是Alipay_LegacyExpress，
创建订单和支付都OK了，但是不执行 $gateway->setNotifyUrl('http://system.xxx.com/alipay_notify');里的回调url。

public function alipay_notify(Request $request){
        die($request);
}
这样写都不执行，请问是怎么回事呢？

**Comment by lokielse** [comment]
你本地先测试一下，参数随便写。
有些开发框架默认POST需要csrf token

**Comment by rockleeyuetian** [comment]
谢谢老大！确实是csrf token的问题，忘记添加NotifyUrl了，用的是laravel框架
