### ISSUE TITLE
您好，异步通知 The `sign_type` is required 错误是什么情况？

### ISSUE THREAD

**Issue by SimuraEpona** [lokielse/omnipay-alipay#79]
您好，我使用的是Lumen5.2，在使用Aop方法执行异步通知的方法里我是这样写的。
```php
$gateway->setSignType('RSA2');

$result = $gateway->completePurchase(['params' => $request->all()]);
//如果直接写$gateway->completePurchase();的话会出现params is required 错误，所以改成了这样子。

```
出现 The `sign_type` is required 错误，使用的是沙箱测试环境。请问是哪里出现了问题？ 谢谢

**Comment by lokielse** [comment]
请提供一下`$request->all()`的值

**Comment by SimuraEpona** [comment]
您好，我直接 return $request->all() 返回的是一个空数组。我按照之前的Issues在return之前使用
```php
Log::info('Alipay Notify gateway: ' . serialize($this->gateway));
```
记录下来的内容是有数据的，里面也有sign type内容。

**Comment by SimuraEpona** [comment]
不好意思，是我弄错了，之前我的notify路由放在了jwt里面，因此返回了空数组。 现在已经跑通了。谢谢您的回复
