### ISSUE TITLE
我从支付宝这边get到的支付链接有时效限制么？

### ISSUE THREAD

**Issue by X-Bird** [lokielse/omnipay-alipay#8]
1. 前端提交价钱
2. 后端生成订单后到支付宝取得安全支付连接
3. 前端跳转付费
4. 如果这里支付没有完成，我能保存这个安全支付链接以便下次使用不用重庆请求，可以么？

**Comment by lokielse** [comment]
针对你提的问题，刚提交了代码
```php
//通过以下代码对过期失效进行设置(单位是minute)
$gateway->setExpireTime(60*24);
```

**Comment by X-Bird** [comment]
many thx ~ 么么哒～

**Comment by X-Bird** [comment]
Call to undefined method Omnipay\Alipay\ExpressGateway::setExpireTime()

**Comment by X-Bird** [comment]
用不了，但是我看你代码里面有写，但是不知道为什么继承不到。。

**Comment by lokielse** [comment]
修复了~ 请更新到最新版。
