### ISSUE TITLE
执行回调函数的时候出现，The signature is not match，是签名不匹配吗

### ISSUE THREAD

**Issue by limingjundawn** [lokielse/omnipay-alipay#81]
public function alipay(){
        $gateway = Omnipay::create('Alipay_AopF2F');
        $gateway->setAppId(Config::get('alipay.app_id'));
        $gateway->setPrivateKey(Config::get('alipay.merchant_private_key'));
        $gateway->setAlipayPublicKey(Config::get('alipay.alipay_public_key'));
        $gateway->setNotifyUrl(Config::get('alipay.notify_url'));
        $request = $gateway->completePurchase();

        $request->setParams($_POST); //Optional

        try {
            /** @var \Omnipay\Alipay\Responses\AopCompletePurchaseResponse $response */
            $response = $request->send();

            if($response->isPaid()){
                /**
                 * Payment is successful
                 */
                die('success'); //The response should be 'success' only
            }else{
                /**
                 * Payment is not successful
                 */
                die('fail');
            }
        } catch (Exception $e) {
            /**
             * Payment is not successful
             */
            die('fail');
        }
    }

**Comment by lokielse** [comment]
回调签名不匹配，应该是支付宝公钥有误。

**Comment by yanggg1133** [comment]
终于弄好了。支付宝说明语焉不详啊，我们是做自动售货机软件的，足足花了一天时间啊。。。瞎猜猜对的

1.notify 使用的是 支付宝公钥 而不是商户自己的公钥
2.notify 手机支付 使用的是 appid 对应的 支付宝公钥即开放平台的app对应的支付宝公钥
         而不是mapi 对应的支付宝公钥

希望对后来人有所帮助

**Comment by yanggg1133** [comment]
详细请看 http://blog.csdn.net/zhangfeng1133/article/details/68485178

**Comment by yanggg1133** [comment]
除了 签名验证 后面几部没有验证

/*
         *
         服务器异步通知（notify_url）是支付宝服务器主动向商户发送的通知，只有当订单的交易状态改变时才会触发，可以防止因网络等原因引起的丢单问题。对同步通知和异步通知结果的处理步骤大致相同，只是处理完成后的返回值不同。

            1.      验证签名

            在通知返回参数列表中，除去sign、sign_type两个参数外，凡是通知返回回来的参数皆是要签名的参数，具体的签名步骤与请求时相同。

            如果新得到的签名与支付宝返回的签名相同，则签名验证成功。

            2.      判断是否是支付宝服务器发来的处理结果

            为了防止某些人伪造支付宝发来的处理消息，还要验证消息的合法性，有以下三个方法：
                2.1验证消息是否是支付宝发出
                    paraArray
                    notify_id
                    sign
                2.2 活动是否是支付宝服务器发来的青球员的验证结果
                    notify_id

                2.3  获得远程服务器的ATN结果
                     strUrl
                     timeout

            第五步：需要严格按照如下描述校验通知数据的正确性。
            1、商户需要验证该通知数据中的out_trade_no是否为商户系统中创建的订单号，
            2、判断total_amount是否确实为该订单的实际金额（即商户订单创建时的金额），
            3、校验通知中的seller_id（或者seller_email) 是否为out_trade_no这笔单据的对应的操作方（
            有的时候，一个商户可能有多个seller_id/seller_email），
            4、验证app_id是否为该商户本身。上述1、2、3、4有任何一个验证不通过，则表明本次通知是异常通知，
            务必忽略。在上述验证通过后商户必须根据支付宝不同类型的业务通知，正确的进行不同的业务处理，
            并且过滤重复的通知结果数据。在支付宝的业务通知中，只有交易通知状态为TRADE_SUCCESS或TRADE_FINISHED时，
            支付宝才会认定为买家付款成功。

**Comment by tudouya** [comment]
@yanggg1133 我在使用"Alipay_AopApp"进行支付时，支付宝进行异步通知时，程序也报了"The signature is not match"错误，我看了您的博客，我在支付宝申请了两个应用，一个使用的是rsa,一个使用的是rsa2,请问是因为这个原因才导致验签失败的么？
