### ISSUE TITLE
Alipay_LegacyExpress 支付后回调 提示

### ISSUE THREAD

**Issue by leoliuxd** [lokielse/omnipay-alipay#86]
$this->defaultgatewaytype = "Alipay_LegacyExpress";
        $this->gateway = Omnipay::create($this->defaultgatewaytype);
        $this->setGateWay();
        print_r($this->gatewayconfig);
        print_r('----------');
        print_r($this->gateway);
        exit();
        Log::info('call doNotifyUrlAlipayLegacyExpress');
        $options = array_merge($_POST, $_GET);

        //Don't use $_REQUEST for may contain $_COOKIE
        Log::info($options);
        $req = $this->gateway->completePurchase($options);
        /**
         * @var AopTradeAppPayResponse $response
         */
//        $response = $req->send();

        try {
            $response = $req->send();
            if($response->isPaid()){
                Log::info("pay success");
                Log::info($response);
                /**
                 * Payment is successful
                 */
                die('success'); //The notify response should be 'success' only
            }else{
                /**
                 * Payment is not successful
                 */
                Log::info("pay fail");
                Log::info($response);
                die('fail'); //The notify response
            }
        } catch (Exception $e) {
            /**
             * Payment is not successful
             */
            Log::info("pay exception");
            Log::info($e);
            die('fail'); //The notify response
        }
log 中提示：[2017-05-07 03:44:27] local.ERROR: exception 'Omnipay\Common\Exception\InvalidRequestException' with message 'The signature is not match' in /data/feikepay/vendor/lokielse/omnipay-alipay/src/Requests/LegacyNotifyRequest.php:142 

看了下走MD5验证方式，问题出在哪里呢

**Comment by mingmingxianseng** [comment]
看了下代码 ，发现他的doc写错了，
`
 $request = $gateway->completePurchase();
 $request->setParams($_POST);
`

**Comment by leoliuxd** [comment]
$_GET中有个_url='xxx',会导致校验不通过。当时测试了下用$_POST,好像也不行，对照官方的sdk，其中有设置cacert.pem 的步骤，这里面没有找到设置的入口。
