### ISSUE TITLE
貌似支付宝的统一收单交易创建接口没有...

### ISSUE THREAD

**Issue by xiam123** [lokielse/omnipay-alipay#87]
接口名称: **alipay.trade.create**

https://doc.open.alipay.com/docs/api.htm?spm=a219a.7386797.0.0.mn4XIs&docType=4&apiId=1046

啊哈~希望能加上去

**Comment by lokielse** [comment]
这个接口的应用场景是什么？生成的trade_no如何使用呢？

**Comment by xiam123** [comment]
通过扫二维码,显示商品信息,购买商品,创建订单,根据返回的trade_no操作后续流程.嗯,应该是这样的

**Comment by lokielse** [comment]
https://doc.open.alipay.com/docs/api.htm?spm=a219a.7395905.0.0.UOEFry&docType=4&apiId=862

这个接口可以？`Alipay_AopF2F 	Alipay Face To Face Gateway 	当面付 - new`

**Comment by xiam123** [comment]
吃惊,这个接口我没注意,我去好好看看,先在此多谢大佬了

**Comment by xiam123** [comment]
仔细看了下,你提供的这个接口,需要先生成订单,并把订单传到支付宝,然后根据这次的订单支付,precreate和create还有有些差别的

**Comment by lokielse** [comment]
https://doc.open.alipay.com/docs/doc.htm?&docType=1&articleId=105591

根据这个文档，区别在这里：

- `alipay.trade.precreate` 是用户用支付宝扫描`非支付宝终端`的情景下使用，比如客制化的POS机
- `alipay.trade.create` 是用户在支付宝内`webview`中点击付款按钮后，服务端通过此接口创建订单，并通过`JSAPI`发起支付

**Comment by xiam123** [comment]
嗯嗯,对的,因为根据我们的业务,是需要一个网页去支持的,我这几天把功能先搞定了,具体的优化暂时性的置后了.另外...你找的这个文档,我找了好久没找到..好尴尬呐,还好最后也出来了...
