### ISSUE TITLE
refund 退款该如何使用？nginx+php-fpm，php7.0环境，nginx报错502！

### ISSUE THREAD

**Issue by SimonFuu** [lokielse/omnipay-alipay#88]
根据#22 中说的refund进行退款，但是nginx却报502错误，相关Nginx错误日志如下：
> 2017/05/15 18:25:02 [error] 18728#0: *275 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: xxxx, request: "GET /v1/refund HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxxx"

相关代码如下：
```
app() -> configure('alipay');
$gateway = Omnipay::create('Alipay_AopApp');
$gateway->production();
foreach (config('alipay.default') as $k => $v) {  # 设置相关参数，包含app_id，sign_type，private_key，alipay_public_key，version
    if ($k !== 'notify_url') {
        $gateway->setParameter($k, $v);
    }
}
$req = $gateway->refund();
$biz['out_trade_no'] = '201705151813';
$biz['refund_amount'] = 0.01;  # 退款金额
ksort($biz);
$req->setBizContent($biz);
$res = $req -> send();
```

具体想了解一下，refund使用方式是否正确？

**Comment by SimonFuu** [comment]
nginx 报错原因已经找到，本地cUrl版本问题吧。

**Comment by gaodacheng** [comment]
如果问题解决了，请选择关闭本issue @SimonFuu
