### ISSUE TITLE
Alipay Deferred Payment - Feature Request

### ISSUE THREAD

**Issue by Wolfsun** [lokielse/omnipay-alipay#9]
Does Alipay support deferred payment (authorise and capture). For example see PayPal: https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/authcapture/. See "One Authorization, Multiple Captures, and a Refund" section for a common workflow in eCommerce. Are there any plans to add this to your omnipay-alipay project, and if not would it be possible?

**Comment by lokielse** [comment]
I'm sorry to tell you that Alipay does not support that. 

There is no solution I could provide for you.:)

**Comment by Wolfsun** [comment]
Ah, no problem, thaks for letting me know.
