### ISSUE TITLE
一直也没看到关闭订单的功能，是没有开发还是我没找到？

### ISSUE THREAD

**Issue by terrywamg** [lokielse/omnipay-alipay#96]
一直也没看到关闭订单的功能，是没有开发还是我没找到？
看代码里已经准备了相关的类，可是没找到调用的方法入口。

**Comment by terrywamg** [comment]
AopTradeCloseRequest 这个类好像是用来关闭订单的，

**Comment by gaodacheng** [comment]
Hi, @terrywamg 我提交了一个PR，添加了关闭订单的调用。[详情请查看](https://github.com/lokielse/omnipay-alipay/pull/98)
