### ISSUE TITLE
alipay purchase和其他接口不统一还需要BizContent  能不能和其他接口统一哪

### ISSUE THREAD

**Issue by bigrocs** [lokielse/omnipay-alipay#97]
还有回调时候 其他接口是request_params  而alipay是params

**Comment by gdc5percent** [comment]
Hi @bigrocs 

> alipay purchase和其他接口不统一还需要BizContent 能不能和其他接口统一哪

根据支付宝对支付接口的设计，将参数分为公共参数和业务参数两大部分。每一个接口中由于业务不同，则单独需要设置biz_content参数。

参考支付宝接口文档：[点击查看](https://docs.open.alipay.com/204/105465/)
